<template>
  <section class="draw-assistant" :data-stage="stage">
    <div class="assistant-scene">
      <span class="scene-grid" aria-hidden="true"></span><span class="pink-breath" aria-hidden="true"></span><span class="particle-stream" aria-hidden="true"><i></i><i></i><i></i></span><i class="star one" aria-hidden="true">✦</i><i class="star two" aria-hidden="true">✧</i><i class="star three" aria-hidden="true">✦</i><i class="orb" aria-hidden="true"></i><i class="code-glyph" aria-hidden="true">&lt;/&gt;</i>
      <Transition name="character-fade" mode="out-in"><img :key="characterSrc" class="assistant-character" :src="characterSrc" :alt="`原创绘图助手：${currentCopy}`" draggable="false"></Transition>
      <div class="status-bubble" :class="stage" aria-live="polite">
        <img :src="statusIcon" alt="" aria-hidden="true"><span>{{ statusText || currentCopy }}</span>
        <i v-if="isWorking" class="loading-dots" aria-hidden="true"><b></b><b></b><b></b></i><strong v-else-if="stage==='success'" aria-hidden="true">✓</strong><strong v-else-if="stage==='error'" aria-hidden="true">!</strong>
      </div>
    </div>
    <div class="input-shell">
      <span class="sparkle" aria-hidden="true">✦</span><textarea :value="modelValue" :disabled="loading" rows="2" aria-label="绘图需求" placeholder="输入需求，绘图助手帮你生成…" @input="$emit('update:modelValue',$event.target.value)" @keydown="onKeydown"></textarea>
      <button v-if="loading" type="button" class="send stop" aria-label="停止生成" @click="$emit('stop')">■</button><button v-else type="button" class="send" :disabled="!canSend" aria-label="发送绘图需求" @click="$emit('send')"><img src="/draw-assistant/icons/ui/send.svg" alt=""></button>
    </div>
    <div class="mini-progress" aria-label="绘图生成进度">
      <template v-for="(item,index) in steps" :key="item.key"><span :class="stepState(index)"><i>{{ index+1 }}</i><b>{{ item.label }}</b><em v-if="stepState(index).done">✓</em><em v-else-if="stepState(index).error">!</em></span><small v-if="index<steps.length-1" aria-hidden="true"></small></template>
    </div>
    <details class="details"><summary><span>详情与快捷操作</span><img src="/draw-assistant/icons/ui/more.svg" alt=""></summary><div class="detail-actions"><button v-for="item in quickCommands" :key="item" :disabled="loading" @click="$emit('quick',item)">{{ item }}</button></div><div class="messages"><p v-for="(message,index) in messages" :key="index" :class="message.role"><b>{{ message.role==='user'?'我':'助手' }}</b>{{ message.text }}</p></div><footer><button v-if="hasUndo" :disabled="loading" @click="$emit('undo')">撤销上次AI修改</button><button :disabled="loading" @click="$emit('clear')">清空对话</button></footer></details>
  </section>
</template>

<script setup>
import { computed, watch } from 'vue'
const props=defineProps({stage:{type:String,default:'idle'},statusText:{type:String,default:''},modelValue:{type:String,default:''},loading:Boolean,canSend:Boolean,messages:{type:Array,default:()=>[]},quickCommands:{type:Array,default:()=>[]},hasUndo:Boolean})
const emit=defineEmits(['update:modelValue','send','stop','clear','undo','quick'])
const copy={idle:'等待输入',analyzing:'正在理解需求…',generating:'正在生成代码…',assembling:'正在拼装代码…',rendering:'正在渲染图形…',success:'生成完成',error:'生成失败，请重试'},iconNames={idle:'analyze',analyzing:'analyze',generating:'code',assembling:'assemble',rendering:'render',success:'complete',error:'error'},characterNames={idle:'idle',analyzing:'analyzing',generating:'generating',assembling:'assembling',rendering:'rendering',success:'success',error:'error'},steps=[{key:'generating',label:'生成代码'},{key:'assembling',label:'拼装代码'},{key:'rendering',label:'渲染图形'},{key:'success',label:'完成'}],stageIndexes={generating:0,assembling:1,rendering:2,success:3}
let lastProgressIndex=0
watch(()=>props.stage,value=>{if(Number.isInteger(stageIndexes[value]))lastProgressIndex=stageIndexes[value]},{immediate:true})
const currentCopy=computed(()=>copy[props.stage]||copy.idle),characterSrc=computed(()=>`/draw-assistant/seven-states-hd/assistant_${characterNames[props.stage]||'idle'}.png`),statusIcon=computed(()=>`/draw-assistant/icons/status/${iconNames[props.stage]||'analyze'}.svg`),isWorking=computed(()=>['analyzing','generating','assembling','rendering'].includes(props.stage))
function stepState(index){if(props.stage==='idle'||props.stage==='analyzing')return {pending:true,preparing:props.stage==='analyzing'&&index===0};if(props.stage==='error')return {done:index<lastProgressIndex,error:index===lastProgressIndex,pending:index>lastProgressIndex};if(props.stage==='success')return {done:true,final:index===3};const active=stageIndexes[props.stage];return {active:active===index,done:Number.isInteger(active)&&index<active,pending:index>active}}
function onKeydown(event){if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();if(props.canSend&&!props.loading)emit('send')}}
</script>

<style scoped>
.draw-assistant{--p:#7667f6;--v:#9b7df7;--pink:#ef8fdc;--cyan:#63d6e8;position:relative;display:grid;grid-template-rows:minmax(0,1fr) auto;gap:4px;height:100%;min-height:0;padding:8px 10px 5px;overflow:hidden;border-radius:0 0 16px 16px;background:radial-gradient(circle at 18% 30%,rgba(244,184,239,.38),transparent 42%),radial-gradient(circle at 82% 34%,rgba(168,207,255,.34),transparent 46%),linear-gradient(135deg,rgba(255,240,252,.96),rgba(239,233,255,.95) 48%,rgba(229,246,255,.94));color:#202446}
.assistant-scene{position:relative;min-height:0;overflow:hidden;border-radius:14px}.scene-grid{position:absolute;inset:0;opacity:.28;background-image:radial-gradient(circle,#8576d524 1px,transparent 1.5px),linear-gradient(#8d7ae20a 1px,transparent 1px),linear-gradient(90deg,#8d7ae20a 1px,transparent 1px);background-size:14px 14px,28px 28px,28px 28px;mask-image:linear-gradient(to left,#000b,transparent 78%);animation:gridDrift 9s linear infinite}.pink-breath{position:absolute;left:-8%;top:-18%;width:72%;height:110%;border-radius:50%;background:radial-gradient(circle,#f28dde59 0,#f4b7e62e 38%,transparent 70%);filter:blur(8px);animation:pinkBreath 6.4s ease-in-out infinite}.particle-stream{position:absolute;z-index:1;left:37%;top:38%;width:32%;height:30%;transform:rotate(-8deg)}.particle-stream i{position:absolute;width:5px;height:5px;border-radius:50%;background:linear-gradient(135deg,#fff,#dfb5ff);box-shadow:0 0 8px #c995ff80;opacity:.35;animation:particleFlow 6s ease-in-out infinite}.particle-stream i:nth-child(1){left:6%;top:58%}.particle-stream i:nth-child(2){left:42%;top:30%;animation-delay:-2s}.particle-stream i:nth-child(3){left:76%;top:52%;animation-delay:-4s}.star{position:absolute;z-index:1;color:#fff;text-shadow:0 0 10px #9b7df7;font-style:normal;animation:starPulse 5.5s ease-in-out infinite}.star.one{top:12%;left:7%;font-size:12px}.star.two{top:24%;left:48%;font-size:9px;animation-delay:-1.8s}.star.three{top:44%;right:12%;font-size:8px;animation-delay:-3.4s}.orb{position:absolute;right:4%;bottom:5%;width:66px;height:66px;border:1px solid #a78bfa2e;border-radius:50%;box-shadow:0 0 28px #63d6e82d;animation:orbFloat 8s ease-in-out infinite}.code-glyph{position:absolute;right:12%;top:56%;color:#7667f61c;font:700 16px/1 Consolas,monospace;transform:rotate(-6deg)}
.assistant-character{position:absolute;z-index:2;left:2%;bottom:28px;display:block;width:clamp(190px,57%,320px);height:calc(100% - 8px);max-height:100%;object-fit:contain;object-position:left bottom;filter:drop-shadow(0 10px 16px #5c49ad26);user-select:none}.status-bubble{position:absolute;z-index:3;top:29%;left:43%;display:flex;align-items:center;gap:8px;width:min(48%,244px);min-height:46px;padding:9px 13px;border:1px solid #8469f624;border-radius:21px;background:#ffffffcf;box-shadow:0 10px 30px #745bdc1a,inset 0 1px #fff;backdrop-filter:blur(12px);color:var(--p);font-size:12.5px;font-weight:750}.status-bubble:before{content:'';position:absolute;left:-7px;bottom:14px;width:12px;height:12px;border-left:1px solid #8469f624;border-bottom:1px solid #8469f624;background:#ffffffe3;transform:rotate(45deg)}.status-bubble>img{flex:0 0 auto;width:24px;height:24px}.status-bubble>span{position:relative;z-index:1;min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.status-bubble>strong{margin-left:auto}.status-bubble.success{color:#32877a}.status-bubble.error{color:#cc5474;background:#fff8facf}.loading-dots{display:flex;gap:3px;margin-left:auto}.loading-dots b{width:4px;height:4px;border-radius:50%;background:currentColor;animation:dot 1.05s infinite ease-in-out}.loading-dots b:nth-child(2){animation-delay:.14s}.loading-dots b:nth-child(3){animation-delay:.28s}
.input-shell{position:absolute;z-index:4;left:10px;right:10px;bottom:42px;display:grid;grid-template-columns:18px minmax(0,1fr) 42px;align-items:center;gap:6px;min-height:52px;padding:5px 6px 5px 12px;border:1px solid #7c6af638;border-radius:18px;background:#fffffff0;box-shadow:0 8px 22px #4c3b9417;backdrop-filter:blur(10px)}.sparkle{color:var(--v);font-size:14px}.input-shell textarea{min-width:0;resize:none;border:0;outline:0;background:transparent;color:#28324c;font:11px/1.4 'Microsoft YaHei',sans-serif}.send{display:grid;place-items:center;width:42px;height:42px;padding:0;border:0;border-radius:50%;background:linear-gradient(135deg,var(--cyan),var(--v),var(--pink));box-shadow:0 7px 16px #8b5cf647;color:#fff}.send img{width:42px;height:42px}.send.stop{font-size:14px}
.mini-progress{position:relative;z-index:4;display:flex;align-items:center;justify-content:space-between;min-height:22px;margin-bottom:16px;padding:0 5px;color:#989db2;font-size:9px}.mini-progress>span{position:relative;display:flex;align-items:center;gap:3px;white-space:nowrap}.mini-progress>span:after{content:'';position:absolute;left:0;right:0;bottom:-3px;height:2px;border-radius:3px;background:transparent}.mini-progress i{display:grid;place-items:center;width:16px;height:16px;border-radius:50%;background:#ffffff82;color:#8e92a8;font-style:normal;font-size:8px}.mini-progress em{color:#4fc8ad;font-style:normal}.mini-progress>small{flex:1;max-width:32px;height:1px;margin:0 3px;background:linear-gradient(90deg,#a99cf64a,#63d6e844)}.mini-progress .done{color:#65748f}.mini-progress .done i{color:#fff;background:#6bd1bd}.mini-progress .active{color:var(--p);font-weight:800}.mini-progress .active i,.mini-progress .final i{color:#fff;background:linear-gradient(135deg,var(--cyan),var(--v),var(--pink))}.mini-progress .active:after,.mini-progress .final:after{background:linear-gradient(90deg,var(--cyan),var(--v),var(--pink))}.mini-progress .error{color:#cc5474}.mini-progress .error i{color:#fff;background:#ea7997}
.details{position:absolute;z-index:5;left:0;right:0;bottom:1px;min-height:15px}.details summary{display:flex;align-items:center;justify-content:center;gap:4px;color:#7882a0;font-size:9px;cursor:pointer;list-style:none}.details summary img{width:14px;height:14px}.details[open]{max-height:130px;overflow:auto;padding:7px;border:1px solid #8d7ae225;border-radius:12px;background:#ffffffed;box-shadow:0 8px 20px #5c49ad1f}.detail-actions{display:flex;gap:5px;overflow-x:auto;padding:3px 0}.detail-actions button,.details footer button{padding:4px 7px;font-size:9px}.messages{display:grid;gap:4px}.messages p{margin:0;padding:5px 7px;border-radius:8px;background:#fff;font-size:9px;white-space:pre-wrap}.messages p.user{background:#ede9ff}.messages b{display:block;color:var(--v)}.details footer{display:flex;justify-content:flex-end;gap:5px;margin-top:4px}
.character-fade-enter-active,.character-fade-leave-active{transition:opacity .22s ease}.character-fade-enter-from,.character-fade-leave-to{opacity:0}.assistant-character{animation:assistantFloat 4.2s ease-in-out infinite}.draw-assistant[data-stage="error"] .pink-breath,.draw-assistant[data-stage="error"] .particle-stream,.draw-assistant[data-stage="error"] .star,.draw-assistant[data-stage="error"] .orb{animation-duration:10s;opacity:.22}@keyframes assistantFloat{0%,100%{transform:translateY(0)}50%{transform:translateY(-6px)}}@keyframes pinkBreath{0%,100%{opacity:.52;transform:scale(.96) translate3d(0,0,0)}50%{opacity:.88;transform:scale(1.08) translate3d(4%,2%,0)}}@keyframes particleFlow{0%,100%{opacity:.16;transform:translate3d(-8px,7px,0) scale(.75)}50%{opacity:.52;transform:translate3d(18px,-7px,0) scale(1.05)}}@keyframes gridDrift{to{background-position:14px 0,28px 0,28px 0}}@keyframes starPulse{0%,100%{opacity:.28;transform:scale(.8)}50%{opacity:.82;transform:scale(1.12)}}@keyframes orbFloat{0%,100%{transform:translate3d(0,0,0);opacity:.42}50%{transform:translate3d(-8px,-5px,0);opacity:.75}}@keyframes dot{0%,70%,100%{opacity:.25;transform:translateY(0)}35%{opacity:1;transform:translateY(-2px)}}
@media(max-height:800px){.draw-assistant{padding:6px 9px 4px;gap:3px}.assistant-character{bottom:24px;width:clamp(175px,55%,270px);height:calc(100% - 4px)}.status-bubble{top:26%;left:43%;min-height:40px;padding:7px 10px;font-size:11.5px}.status-bubble>img{width:22px;height:22px}.input-shell{left:9px;right:9px;bottom:38px;min-height:48px}.send,.send img{width:38px;height:38px}.mini-progress{min-height:20px;margin-bottom:14px}}@media(max-width:420px){.assistant-character{width:55%}.status-bubble{left:42%;width:54%;padding-inline:8px;font-size:11px}.mini-progress b{font-size:8px}.mini-progress>small{margin-inline:1px}.input-shell{grid-template-columns:15px minmax(0,1fr) 38px}}@media(prefers-reduced-motion:reduce){.draw-assistant *{animation:none!important;transition:none!important}}button:disabled{cursor:not-allowed;opacity:.5}
</style>
