package com.dropai.generator.blueprint;

import com.dropai.generator.model.GenerationModel;
import com.fasterxml.jackson.databind.*;
import java.security.MessageDigest;
import java.util.*;
import static com.dropai.generator.blueprint.ProjectBlueprint.*;
import static com.dropai.generator.model.GenerationModel.*;

public final class BlueprintPipeline {
    private static final List<FieldSpec> SYSTEM_FIELDS=List.of(field("id","id",FieldType.INTEGER,"ID",true,false),field("createdTime","created_time",FieldType.DATETIME,"创建时间",false,false),field("updatedTime","updated_time",FieldType.DATETIME,"更新时间",false,false),field("deleted","deleted",FieldType.BOOLEAN,"删除标记",false,false));
    private final ObjectMapper mapper=new ObjectMapper().enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS);
    public ProjectBlueprint parse(byte[] json)throws Exception{return mapper.readValue(json,ProjectBlueprint.class);}
    public GenerationModel normalize(ProjectBlueprint input)throws Exception{
        validate(input); Map<String,EntitySpec> originals=new LinkedHashMap<>(); input.entities().forEach(e->originals.put(e.name(),e));
        List<RelationModel> relations=new ArrayList<>(); Map<String,List<FieldSpec>> relationFields=new HashMap<>();
        for(RelationSpec r:input.relations()){
            if(r.type()!=RelationType.ONE_TO_MANY)throw new IllegalArgumentException("ITERATION_2_ONLY_ONE_TO_MANY");
            EntitySpec source=originals.get(r.sourceEntity()),target=originals.get(r.targetEntity());
            String fk=r.foreignKeyField(); String col=snake(fk); String display=lowerFirst(source.name())+"Name";
            relations.add(new RelationModel(r.name(),source.name(),target.name(),source.tableName(),target.tableName(),fk,col,source.displayField(),fieldColumn(source,source.displayField()),display,r.required(),r.onDelete()));
            relationFields.computeIfAbsent(target.name(),k->new ArrayList<>()).add(field(fk,col,FieldType.INTEGER,source.title(),r.required(),true));
        }
        List<EntitySpec> normalizedEntities=new ArrayList<>();
        for(EntitySpec e:input.entities()){List<FieldSpec> fs=new ArrayList<>(SYSTEM_FIELDS);fs.addAll(e.fields());fs.addAll(relationFields.getOrDefault(e.name(),List.of()));normalizedEntities.add(new EntitySpec(e.name(),e.tableName(),e.title(),e.description(),e.displayField(),e.displayConfig(),List.copyOf(fs),e.indexes()));}
        ProjectBlueprint normalized=new ProjectBlueprint(input.schemaVersion(),input.project(),input.template(),List.copyOf(normalizedEntities),input.relations(),input.modules(),input.roles(),input.permissions(),input.businessFlows(),input.capabilities(),input.generation());
        String hash=sha256(mapper.writeValueAsBytes(normalized)); Set<String> referenced=new HashSet<>();relations.forEach(r->referenced.add(r.sourceEntity()));
        List<EntityModel> entities=new ArrayList<>();
        for(EntitySpec e:normalizedEntities){ModuleSpec m=input.modules().stream().filter(x->x.entity().equals(e.name())).findFirst().orElseThrow();RelationModel parent=relations.stream().filter(r->r.targetEntity().equals(e.name())).findFirst().orElse(null);List<FieldModel> fields=e.fields().stream().map(f->mapField(f,parent!=null&&f.name().equals(parent.foreignKeyName()))).toList();entities.add(new EntityModel(e.name(),lowerFirst(e.name()),e.tableName(),e.title(),m.apiPath(),e.displayField(),e.displayConfig()==null?"{"+e.displayField()+"}":e.displayConfig().template(),referenced.contains(e.name()),fields,parent));}
        List<PermissionModel> permissions=input.permissions().stream().map(p->new PermissionModel(p.moduleCode(),p.action().name(),p.moduleCode()+":"+p.action().name().toLowerCase(Locale.ROOT),p.description())).toList();
        List<FileGenerationPlan> plans=plans(normalized,entities,relations,permissions,hash);return new GenerationModel(normalized,List.copyOf(entities),List.copyOf(relations),permissions,plans,hash);
    }
    private void validate(ProjectBlueprint bp){if(!"springboot-vue-template".equals(bp.template().id()))throw new IllegalArgumentException("TEMPLATE_UNSUPPORTED");if(bp.entities()==null||bp.entities().isEmpty()||bp.modules()==null)throw new IllegalArgumentException("STRUCTURE_INVALID");Set<String> names=new HashSet<>();bp.entities().forEach(e->{names.add(e.name());if(!e.name().matches("[A-Z][A-Za-z0-9]*")||!e.tableName().matches("[a-z][a-z0-9_]*"))throw new IllegalArgumentException("UNSAFE_IDENTIFIER");});bp.modules().forEach(m->{if(!names.contains(m.entity()))throw new IllegalArgumentException("MODULE_ENTITY_NOT_FOUND");});bp.relations().forEach(r->{if(!names.contains(r.sourceEntity())||!names.contains(r.targetEntity())||!r.targetEntity().equals(r.foreignKeyEntity()))throw new IllegalArgumentException("RELATION_INVALID");});Set<String> ps=new HashSet<>();bp.permissions().forEach(p->ps.add(p.moduleCode()+":"+p.action().name().toLowerCase(Locale.ROOT)));bp.roles().forEach(r->{if(!ps.containsAll(r.permissionCodes()))throw new IllegalArgumentException("ROLE_PERMISSION_NOT_FOUND");});}
    private List<FileGenerationPlan> plans(ProjectBlueprint bp,List<EntityModel> entities,List<RelationModel> relations,List<PermissionModel> permissions,String hash){String pkg=bp.project().basePackage().replace('.','/');List<FileGenerationPlan> out=new ArrayList<>();for(EntityModel e:entities){Map<String,Object> model=new LinkedHashMap<>();model.put("project",bp.project());model.put("entity",e);model.put("entities",entities);model.put("relations",relations);model.put("permissions",permissions);String v=e.variableName();add(out,"backend:entity:"+v,GeneratorType.BACKEND,"entity.java.ftl","backend/src/main/java/"+pkg+"/entity/"+e.className()+".java",hash,model);add(out,"backend:dto:"+v,GeneratorType.BACKEND,"dto.java.ftl","backend/src/main/java/"+pkg+"/dto/"+e.className()+"DTO.java",hash,model);add(out,"backend:query:"+v,GeneratorType.BACKEND,"query.java.ftl","backend/src/main/java/"+pkg+"/dto/"+e.className()+"QueryDTO.java",hash,model);add(out,"backend:vo:"+v,GeneratorType.BACKEND,"vo.java.ftl","backend/src/main/java/"+pkg+"/vo/"+e.className()+"VO.java",hash,model);add(out,"backend:mapper:"+v,GeneratorType.BACKEND,"mapper.java.ftl","backend/src/main/java/"+pkg+"/mapper/"+e.className()+"Mapper.java",hash,model);add(out,"backend:service:"+v,GeneratorType.BACKEND,"service.java.ftl","backend/src/main/java/"+pkg+"/service/"+e.className()+"Service.java",hash,model);add(out,"backend:service-impl:"+v,GeneratorType.BACKEND,"service-impl.java.ftl","backend/src/main/java/"+pkg+"/service/impl/"+e.className()+"ServiceImpl.java",hash,model);add(out,"backend:controller:"+v,GeneratorType.BACKEND,"controller.java.ftl","backend/src/main/java/"+pkg+"/controller/"+e.className()+"Controller.java",hash,model);add(out,"frontend:api:"+v,GeneratorType.FRONTEND,"api.ts.ftl","frontend/src/api/"+v+".ts",hash,model);add(out,"frontend:types:"+v,GeneratorType.FRONTEND,"types.ts.ftl","frontend/src/types/"+v+".ts",hash,model);add(out,"frontend:list:"+v,GeneratorType.FRONTEND,"index.vue.ftl","frontend/src/views/"+v+"/index.vue",hash,model);add(out,"frontend:form:"+v,GeneratorType.FRONTEND,"form.vue.ftl","frontend/src/views/"+v+"/form.vue",hash,model);add(out,"frontend:detail:"+v,GeneratorType.FRONTEND,"detail.vue.ftl","frontend/src/views/"+v+"/detail.vue",hash,model);}Map<String,Object> all=new LinkedHashMap<>();all.put("project",bp.project());all.put("entities",entities);all.put("relations",relations);all.put("permissions",permissions);add(out,"sql:database",GeneratorType.SQL,"database.sql.ftl","sql/database.sql",hash,all);return List.copyOf(out);}
    private static void add(List<FileGenerationPlan> o,String k,GeneratorType t,String tm,String p,String h,Map<String,Object> m){o.add(new FileGenerationPlan(k,t,tm,p,h,Set.of(),m));}
    private static FieldModel mapField(FieldSpec f,boolean relation){return new FieldModel(f.name(),f.columnName(),javaType(f.type()),tsType(f.type()),sqlType(f),f.title(),f.required(),f.searchable(),f.listVisible(),f.formVisible(),relation);}
    private static String fieldColumn(EntitySpec e,String name){return e.fields().stream().filter(f->f.name().equals(name)).findFirst().orElseThrow().columnName();}
    private static String javaType(FieldType t){return switch(t){case INTEGER->"Long";case DECIMAL->"java.math.BigDecimal";case BOOLEAN->"Boolean";case DATE->"java.time.LocalDate";case DATETIME->"java.time.LocalDateTime";default->"String";};}private static String tsType(FieldType t){return switch(t){case INTEGER,DECIMAL->"number";case BOOLEAN->"boolean";default->"string";};}private static String sqlType(FieldSpec f){return switch(f.type()){case INTEGER->"BIGINT";case DECIMAL->"DECIMAL("+(f.precision()==null?12:f.precision())+","+(f.scale()==null?2:f.scale())+")";case BOOLEAN->"TINYINT(1)";case DATE->"DATE";case DATETIME->"DATETIME";case TEXT->"TEXT";default->"VARCHAR("+(f.length()==null?255:f.length())+")";};}
    private static FieldSpec field(String n,String c,FieldType t,String title,boolean req,boolean form){return new FieldSpec(n,c,t,title,req,false,null,null,null,null,List.of(),false,true,form);}private static String snake(String v){return v.replaceAll("([a-z0-9])([A-Z])","$1_$2").toLowerCase(Locale.ROOT);}private static String lowerFirst(String v){return Character.toLowerCase(v.charAt(0))+v.substring(1);}public static String sha256(byte[] v){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v));}catch(Exception e){throw new IllegalStateException(e);}}
}
