<template><main class="page"><header><div class="brand"><i>D</i><span><b>Dokiai Academic</b><small>SCHOOL STATISTICS</small></span></div><div class="total"><small>本校学生累计充值金额</small><strong>¥{{ money(data.totalRechargeAmount) }}</strong></div><button @click="signOut">退出</button></header><section class="welcome"><small>READ-ONLY SCHOOL OVERVIEW</small><h1>{{ data.schoolName||'学校统计' }}</h1><p>学校编号 {{ data.schoolCode||'--' }} · 本页面仅展示本校汇总数据，不提供学生资料或订单明细。</p><nav><button v-for="r in ranges" :key="r.key" :class="{active:range===r.key}" @click="range=r.key;load()">{{ r.label }}</button></nav></section><div class="charts"><section><h2>本校充值金额趋势图</h2><p>仅统计支付成功净额</p><div ref="rechargeEl" class="chart"></div></section><section><h2>本校新增注册人数趋势图</h2><p>按新用户注册时间统计</p><div ref="registerEl" class="chart"></div></section></div></main></template>
<script setup>
import * as echarts from 'echarts';import {nextTick,onBeforeUnmount,onMounted,ref} from 'vue';import {useRouter} from 'vue-router';import {getSchoolViewerStatistics,logout} from '../../api/rewrite'
const router=useRouter(),range=ref('30d'),ranges=[{key:'7d',label:'最近7天'},{key:'30d',label:'最近30天'},{key:'monthly',label:'近一年'}],data=ref({}),rechargeEl=ref(),registerEl=ref();let rechargeChart,registerChart
const money=v=>Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});const date=x=>String(x.day||'').slice(0,10)
function draw(){rechargeChart?.dispose();registerChart?.dispose();rechargeChart=echarts.init(rechargeEl.value);registerChart=echarts.init(registerEl.value);const base={tooltip:{trigger:'axis'},grid:{left:48,right:20,top:25,bottom:35},xAxis:{type:'category',axisLine:{lineStyle:{color:'#dcd6ee'}}},yAxis:{type:'value',splitLine:{lineStyle:{color:'#eeeaf6'}}}};rechargeChart.setOption({...base,xAxis:{...base.xAxis,data:(data.value.rechargeTrend||[]).map(date)},series:[{type:'line',smooth:true,areaStyle:{color:'#e9e1ff'},lineStyle:{color:'#7056df',width:3},itemStyle:{color:'#7056df'},data:(data.value.rechargeTrend||[]).map(x=>Number(x.value||0))}]});registerChart.setOption({...base,xAxis:{...base.xAxis,data:(data.value.registrationTrend||[]).map(date)},series:[{type:'bar',barMaxWidth:24,itemStyle:{color:'#d765ae',borderRadius:[6,6,0,0]},data:(data.value.registrationTrend||[]).map(x=>Number(x.value||0))}]})}
async function load(){data.value=await getSchoolViewerStatistics(range.value)||{};await nextTick();draw()}function resize(){rechargeChart?.resize();registerChart?.resize()}async function signOut(){try{await logout()}catch{}sessionStorage.clear();router.replace('/login')}onMounted(()=>{load();window.addEventListener('resize',resize)});onBeforeUnmount(()=>{window.removeEventListener('resize',resize);rechargeChart?.dispose();registerChart?.dispose()})
</script>
<style scoped>.page{min-height:100vh;padding:24px max(28px,calc((100% - 1450px)/2)) 70px;background:linear-gradient(45deg,#fbd7ea,#f7edf5 38%,#edf1f8 65%,#dcebff);color:#292b39}.page>header{display:flex;align-items:center;gap:20px}.brand{display:flex;align-items:center;gap:10px}.brand i{display:grid;place-items:center;width:42px;height:42px;border-radius:12px;background:linear-gradient(145deg,#4198ff,#7658ef 60%,#df66b7);color:#fff;font-style:normal;font-weight:900}.brand span{display:grid}.brand small{color:#8d95a5;font-size:8px}.total{display:grid;margin-left:auto;padding:14px 20px;border:1px solid #e3ddef;border-radius:16px;background:#fff;box-shadow:0 15px 40px #4d416b12}.total small{color:#777f91}.total strong{color:#654ed1;font-size:28px}.page>header>button{border:0;background:none;color:#6855d1}.welcome{margin-top:42px;padding:28px;border:1px solid #e6e1ef;border-radius:23px;background:#ffffffd9}.welcome>small{color:#6e4fff;font-weight:800;letter-spacing:.14em}.welcome h1{margin:8px 0;font-size:38px}.welcome p{color:#7a8191}.welcome nav{display:flex;gap:7px;margin-top:20px}.welcome button{padding:9px 14px;border:1px solid #ddd7e9;border-radius:10px;background:#fff}.welcome button.active{border-color:#8f78e7;background:#f0ebff;color:#654ed1}.charts{display:grid;grid-template-columns:1fr 1fr;gap:16px;margin-top:16px}.charts section{padding:24px;border:1px solid #e5e0ed;border-radius:21px;background:#ffffffdf;box-shadow:0 18px 50px #3e356b12}.charts h2{margin:0}.charts p{margin:6px 0;color:#8b92a2}.chart{height:380px}@media(max-width:850px){.charts{grid-template-columns:1fr}.page>header{align-items:flex-start;flex-wrap:wrap}.total{order:3;width:100%;margin:0}}</style>
