package com.dropai.generator.engine;

import com.dropai.generator.model.GenerationModel;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.LinkedHashMap;
import java.util.Map;

final class ProjectScaffold {
    private ProjectScaffold() {}
    static void write(Path root, GenerationModel model) throws Exception {
        String base = model.source().project().basePackage();
        String pkg = base.replace('.', '/');
        Map<String,String> files = new LinkedHashMap<>();
        files.put("backend/pom.xml", backendPom(model.source().project().name()));
        files.put("backend/src/main/resources/application.yml", applicationYml());
        files.put("backend/src/main/java/"+pkg+"/Application.java", application(base));
        files.put("backend/src/main/java/"+pkg+"/common/Result.java", result(base));
        files.put("backend/src/main/java/"+pkg+"/common/PageResult.java", pageResult(base));
        files.put("backend/src/main/java/"+pkg+"/security/SecurityConfig.java", security(base));
        files.put("backend/src/main/java/"+pkg+"/security/TokenService.java", tokenService(base));
        files.put("backend/src/main/java/"+pkg+"/security/TokenFilter.java", tokenFilter(base));
        files.put("backend/src/main/java/"+pkg+"/controller/AuthController.java", authController(base));
        if(model.entities().size()==1){files.put("backend/src/test/java/"+pkg+"/SingleEntityCrudVerticalSliceTest.java", backendTest(base, model.entity().className()));files.put("backend/src/test/resources/schema-test.sql", testSchema());}
        files.put("frontend/package.json", packageJson());
        files.put("frontend/index.html", indexHtml());
        files.put("frontend/tsconfig.json", tsconfig());
        files.put("frontend/vite.config.ts", viteConfig());
        files.put("frontend/src/main.ts", mainTs());
        files.put("frontend/src/App.vue", appVue());
        files.put("frontend/src/router.ts", routerTs(model));
        files.put("frontend/src/utils/request.ts", requestTs());
        files.put("frontend/src/views/Login.vue", loginVue(model));
        for (var entry : files.entrySet()) { Path target=root.resolve(entry.getKey()); Files.createDirectories(target.getParent()); Files.writeString(target,entry.getValue(),StandardCharsets.UTF_8); }
    }
    static String readme(GenerationModel m){return "# "+m.source().project().title()+"\n\nGenerated by Dokiai Generator Engine 1.0.0.\n\n## Start\n\n1. Execute `sql/database.sql` on MySQL 8.\n2. Run backend: `mvn spring-boot:run`.\n3. Run frontend: `npm install && npm run dev`.\n4. Login with `admin / Admin123!` and change the password before deployment.\n";}
    private static String backendPom(String name){return """
            <?xml version="1.0" encoding="UTF-8"?>
            <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
              <modelVersion>4.0.0</modelVersion><parent><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-parent</artifactId><version>3.3.5</version><relativePath/></parent>
              <groupId>com.dokiai</groupId><artifactId>%s-backend</artifactId><version>1.0.0</version><properties><java.version>17</java.version></properties>
              <dependencies><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-security</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-validation</artifactId></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-jdbc</artifactId></dependency><dependency><groupId>com.mysql</groupId><artifactId>mysql-connector-j</artifactId><scope>runtime</scope></dependency><dependency><groupId>com.h2database</groupId><artifactId>h2</artifactId><scope>test</scope></dependency><dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-test</artifactId><scope>test</scope></dependency><dependency><groupId>org.springframework.security</groupId><artifactId>spring-security-test</artifactId><scope>test</scope></dependency></dependencies>
              <build><plugins><plugin><groupId>org.springframework.boot</groupId><artifactId>spring-boot-maven-plugin</artifactId></plugin></plugins></build>
            </project>
            """.formatted(name);}
    private static String applicationYml(){return "server:\n  port: ${SERVER_PORT:8080}\nspring:\n  application:\n    name: library-system\n  datasource:\n    url: ${DB_URL:jdbc:mysql://127.0.0.1:3306/library_system?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai}\n    username: ${DB_USERNAME:root}\n    password: ${DB_PASSWORD:}\n    driver-class-name: com.mysql.cj.jdbc.Driver\n";}
    private static String testSchema(){return "DROP TABLE IF EXISTS book; CREATE TABLE book(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,created_time TIMESTAMP,updated_time TIMESTAMP,deleted BOOLEAN DEFAULT FALSE,name VARCHAR(200) NOT NULL,isbn VARCHAR(32) NOT NULL,author VARCHAR(100) NOT NULL,status VARCHAR(32) NOT NULL);";}
    private static String application(String p){return "package "+p+";\nimport org.springframework.boot.*;import org.springframework.boot.autoconfigure.*;\n@SpringBootApplication public class Application{public static void main(String[]a){SpringApplication.run(Application.class,a);}}\n";}
    private static String result(String p){return "package "+p+".common; public record Result<T>(boolean success,T data,String message){public static <T> Result<T> ok(T d){return new Result<>(true,d,\"OK\");}}\n";}
    private static String pageResult(String p){return "package "+p+".common; import java.util.List; public record PageResult<T>(List<T> records,long total,int pageNum,int pageSize){}\n";}
    private static String tokenService(String p){return """
            package %s.security;
            import org.springframework.stereotype.*;import javax.crypto.*;import javax.crypto.spec.*;import java.nio.charset.*;import java.time.*;import java.util.*;
            @Service public class TokenService{private static final byte[] KEY="dokiai-library-demo-secret-key-32".getBytes(StandardCharsets.UTF_8);public String create(String user){long exp=Instant.now().plusSeconds(28800).getEpochSecond();String body=user+":"+exp;return Base64.getUrlEncoder().withoutPadding().encodeToString(body.getBytes(StandardCharsets.UTF_8))+"."+sign(body);}public String verify(String token){try{String[]p=token.split("\\\\.");String body=new String(Base64.getUrlDecoder().decode(p[0]),StandardCharsets.UTF_8);if(!sign(body).equals(p[1]))return null;String[]b=body.split(":");return Long.parseLong(b[1])>Instant.now().getEpochSecond()?b[0]:null;}catch(Exception e){return null;}}private String sign(String value){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(KEY,"HmacSHA256"));return Base64.getUrlEncoder().withoutPadding().encodeToString(mac.doFinal(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}}
            """.formatted(p);}
    private static String tokenFilter(String p){return """
            package %s.security;
            import jakarta.servlet.*;import jakarta.servlet.http.*;import org.springframework.security.authentication.*;import org.springframework.security.core.authority.*;import org.springframework.security.core.context.*;import org.springframework.stereotype.*;import org.springframework.web.filter.*;import java.io.*;import java.util.*;
            @Component public class TokenFilter extends OncePerRequestFilter{private final TokenService tokens;public TokenFilter(TokenService t){tokens=t;}protected void doFilterInternal(HttpServletRequest r,HttpServletResponse s,FilterChain c)throws ServletException,IOException{String h=r.getHeader("Authorization");if(h!=null&&h.startsWith("Bearer ")){String u=tokens.verify(h.substring(7));if(u!=null)SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(u,null,List.of(new SimpleGrantedAuthority("ROLE_ADMIN"))));}c.doFilter(r,s);}}
            """.formatted(p);}
    private static String security(String p){return """
            package %s.security;
            import org.springframework.context.annotation.*;import org.springframework.http.*;import org.springframework.security.config.annotation.web.builders.*;import org.springframework.security.config.http.*;import org.springframework.security.crypto.bcrypt.*;import org.springframework.security.crypto.password.*;import org.springframework.security.web.*;import org.springframework.security.web.authentication.*;
            @Configuration public class SecurityConfig{@Bean PasswordEncoder passwordEncoder(){return new BCryptPasswordEncoder();}@Bean SecurityFilterChain chain(HttpSecurity h,TokenFilter f)throws Exception{return h.csrf(c->c.disable()).sessionManagement(s->s.sessionCreationPolicy(SessionCreationPolicy.STATELESS)).authorizeHttpRequests(a->a.requestMatchers("/api/auth/login","/api/health").permitAll().anyRequest().authenticated()).addFilterBefore(f,UsernamePasswordAuthenticationFilter.class).exceptionHandling(e->e.authenticationEntryPoint((r,s,x)->s.sendError(HttpStatus.UNAUTHORIZED.value()))).build();}}
            """.formatted(p);}
    private static String authController(String p){return """
            package %s.controller;
            import %s.common.*;import %s.security.*;import org.springframework.security.crypto.password.*;import org.springframework.web.bind.annotation.*;import java.util.*;
            @RestController @RequestMapping("/api") public class AuthController{private final TokenService tokens;private final PasswordEncoder encoder;private final String passwordHash;public AuthController(TokenService t,PasswordEncoder e){tokens=t;encoder=e;passwordHash=e.encode("Admin123!");}@PostMapping("/auth/login")public Result<Map<String,String>> login(@RequestBody Login r){if(!"admin".equals(r.username())||!encoder.matches(r.password(),passwordHash))throw new IllegalArgumentException("账号或密码错误");return Result.ok(Map.of("token",tokens.create(r.username()),"username",r.username()));}@GetMapping("/health")public Result<String> health(){return Result.ok("UP");}public record Login(String username,String password){}}
            """.formatted(p,p,p);}
    private static String backendTest(String p,String e){return """
            package %s;
            import com.fasterxml.jackson.databind.*;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.*;import org.springframework.boot.test.autoconfigure.web.servlet.*;import org.springframework.boot.test.context.*;import org.springframework.http.*;import org.springframework.test.web.servlet.*;import java.util.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
            @SpringBootTest(properties={"spring.datasource.url=jdbc:h2:mem:book;MODE=MySQL;DB_CLOSE_DELAY=-1","spring.datasource.driver-class-name=org.h2.Driver","spring.datasource.username=sa","spring.datasource.password=","spring.sql.init.mode=always","spring.sql.init.schema-locations=classpath:schema-test.sql"}) @AutoConfigureMockMvc class SingleEntityCrudVerticalSliceTest{@Autowired MockMvc mvc;@Autowired ObjectMapper json;private String token()throws Exception{String request=json.writeValueAsString(Map.of("username","admin","password","Admin123!"));String body=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content(request)).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();return json.readTree(body).path("data").path("token").asText();}@Test void loginAndCrud()throws Exception{String t="Bearer "+token();String create=json.writeValueAsString(Map.of("name","Domain-Driven Design","isbn","9780321125217","author","Eric Evans","status","AVAILABLE"));String created=mvc.perform(post("/api/book").header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content(create)).andExpect(status().isOk()).andReturn().getResponse().getContentAsString();long id=json.readTree(created).path("data").asLong();mvc.perform(get("/api/book/page").header("Authorization",t)).andExpect(status().isOk()).andExpect(jsonPath("$.data.total").value(1));Map<String,Object> update=new LinkedHashMap<>();update.put("id",id);update.put("name","DDD");update.put("isbn","9780321125217");update.put("author","Eric Evans");update.put("status","AVAILABLE");mvc.perform(put("/api/book").header("Authorization",t).contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(update))).andExpect(status().isOk());mvc.perform(delete("/api/book/"+id).header("Authorization",t)).andExpect(status().isOk());}}
            """.formatted(p);}
    private static String packageJson(){return "{\"name\":\"library-system-frontend\",\"private\":true,\"version\":\"1.0.0\",\"type\":\"module\",\"scripts\":{\"dev\":\"vite\",\"build\":\"vue-tsc -b && vite build\"},\"dependencies\":{\"@vitejs/plugin-vue\":\"5.2.1\",\"axios\":\"1.7.9\",\"element-plus\":\"2.9.1\",\"vue\":\"3.5.13\",\"vue-router\":\"4.5.0\"},\"devDependencies\":{\"typescript\":\"5.7.2\",\"vite\":\"6.0.5\",\"vue-tsc\":\"2.2.0\"}}";}
    private static String indexHtml(){return "<div id=\"app\"></div><script type=\"module\" src=\"/src/main.ts\"></script>";}
    private static String tsconfig(){return "{\"compilerOptions\":{\"target\":\"ES2020\",\"module\":\"ESNext\",\"moduleResolution\":\"Bundler\",\"strict\":true,\"skipLibCheck\":true,\"lib\":[\"ES2020\",\"DOM\"]},\"include\":[\"src/**/*.ts\",\"src/**/*.vue\"]}";}
    private static String viteConfig(){return "import {defineConfig,loadEnv} from 'vite';import vue from '@vitejs/plugin-vue';export default defineConfig(({mode})=>{const env=loadEnv(mode,'.','');return{plugins:[vue()],server:{proxy:{'/api':env.VITE_BACKEND_URL||'http://localhost:8080'}}}});";}
    private static String mainTs(){return "import {createApp} from 'vue';import ElementPlus from 'element-plus';import 'element-plus/dist/index.css';import App from './App.vue';import router from './router';createApp(App).use(ElementPlus).use(router).mount('#app');";}
    private static String appVue(){return "<template><router-view/></template>";}
    private static String routerTs(GenerationModel model){StringBuilder s=new StringBuilder("import {createRouter,createWebHistory} from 'vue-router';import Login from './views/Login.vue';");for(var e:model.entities())s.append("import ").append(e.className()).append(" from './views/").append(e.variableName()).append("/index.vue';");s.append("const router=createRouter({history:createWebHistory(),routes:[{path:'/',redirect:'/").append(model.entity().variableName()).append("'},{path:'/login',component:Login}");for(var e:model.entities())s.append(",{path:'/").append(e.variableName()).append("',component:").append(e.className()).append("}");s.append("]});router.beforeEach(to=>to.path!='/login'&&!localStorage.getItem('token')?'/login':true);export default router;");return s.toString();}
    private static String requestTs(){return "import axios from 'axios';const request=axios.create({baseURL:'/api'});request.interceptors.request.use(c=>{const t=localStorage.getItem('token');if(t)c.headers.Authorization=`Bearer ${t}`;return c});export default request;";}
    private static String loginVue(GenerationModel model){return "<script setup lang=\"ts\">import{reactive}from'vue';import{useRouter}from'vue-router';import request from'../utils/request';const form=reactive({username:'admin',password:'Admin123!'});const router=useRouter();async function login(){const r=await request.post('/auth/login',form);localStorage.setItem('token',r.data.data.token);router.push('/"+model.entity().variableName()+"')}</script><template><el-card style=\"max-width:420px;margin:100px auto\"><h2>系统登录</h2><el-input v-model=\"form.username\" placeholder=\"账号\"/><el-input v-model=\"form.password\" type=\"password\" placeholder=\"密码\"/><el-button type=\"primary\" @click=\"login\">登录</el-button></el-card></template>";}
}
