<template>
  <main class="outline-page">
    <nav><button class="brand" @click="router.push('/dashboard')">D <span>DropAI</span></button><WritingV2Steps :current="2"/><button class="ghost" @click="router.push('/writing-generator')">返回文献处理</button></nav>
    <header><span>STEP 2 · DOCUMENT DESIGN CENTER</span><h1>文档设计中心</h1><p>统一确认大纲、图片、表格和联网素材。所有调整自动保存，确认后再进入正文生成。</p></header>
    <section class="panel">
      <div class="asset-tools">
        <div><h3>上传目录替换模板</h3><p>支持 Word/PDF。识别成功后将完全替换当前模板，不进行融合。</p><el-upload v-model:file-list="outlineFiles" :auto-upload="false" :limit="1" accept=".doc,.docx,.pdf"><el-button>选择目录文件</el-button></el-upload><el-button :loading="replacingOutline" :disabled="!outlineFiles.length" @click="replaceOutline">识别并替换大纲</el-button></div>
        <div><h3>上传图片素材</h3><p>支持 JPG、PNG、WEBP，可一次上传多张；上传后自动分析并进入待确认列表。</p><el-upload v-model:file-list="imageFiles" :auto-upload="false" multiple accept=".jpg,.jpeg,.png,.webp"><el-button>选择图片</el-button></el-upload><el-button :loading="uploadingImages" :disabled="!imageFiles.length" @click="uploadImages">上传并识别</el-button></div>
      </div>
      <div class="mode-grid">
        <button v-for="mode in modes" :key="mode.value" :class="{selected:form.documentMode===mode.value}" @click="form.documentMode=mode.value"><b>{{ mode.icon }}</b><strong>{{ mode.label }}</strong><small>{{ mode.description }}</small></button>
      </div>
      <el-form v-if="form.documentMode==='environment'" label-position="top" class="location"><el-form-item label="项目大致地理位置"><el-input v-model="form.projectLocation" placeholder="例如：某市某区某街道、某景区附近或基地名称" maxlength="200"/></el-form-item><p>无需地图点选；该位置将作为后续地图定位与区位图片检索条件。</p></el-form>
      <el-button class="generate" type="primary" size="large" :loading="generating" @click="generate">根据所选模式生成提纲</el-button>
    </section>
    <template v-if="outlineReady">
      <section class="panel outline-shell">
        <div class="head"><div><small>提纲结构</small><h2>{{ currentMode.label }}</h2></div><span>{{ isGeneral ? '按二级标题配置图表数量' : '分析类联网搜图，设计类优先使用上传素材' }}</span></div>
        <article v-for="(chapter,chapterIndex) in flow.chapters" :key="chapter.id" class="chapter">
          <div class="chapter-editor"><b>第 {{ chapter.chapter_no }} 章</b><el-input v-model="chapter.title" maxlength="120" @change="saveChapter(chapter)"/><button @click="moveChapter(chapterIndex,-1)">上移</button><button @click="moveChapter(chapterIndex,1)">下移</button><button class="danger" @click="removeChapter(chapter)">删除</button></div>
          <div v-for="(section,sectionIndex) in chapter.sections" :key="section.id" class="section-editor">
            <div class="section-title"><b>{{ section.section_no }}</b><el-input v-model="section.title" maxlength="160" @change="saveSection(section)"/><span :class="['type',section.content_type]">{{ typeName(section.content_type) }}</span><button @click="moveSection(chapter,sectionIndex,-1)">上移</button><button @click="moveSection(chapter,sectionIndex,1)">下移</button><button class="danger" @click="removeSection(section)">删除</button></div>
            <div class="image-requirements"><small>图片需求（AI 建议，可人工增删和修改）</small><el-tag v-for="(requirement,index) in section.imageRequirements" :key="index" closable @close="removeRequirement(section,index)">{{ requirement }}</el-tag><el-input v-model="section.newRequirement" placeholder="输入图片类型或说明" @keyup.enter="addRequirement(section)"/><button @click="addRequirement(section)">添加</button></div>
            <div v-if="sectionImageTasks(section.id).length" class="image-tasks"><small>图片准备状态</small><span v-for="task in sectionImageTasks(section.id)" :key="task.id" :class="['task',String(task.status).toLowerCase()]"><b>{{ task.requirement_name }}</b>{{ taskStatus(task.status) }}</span></div>
            <div class="counts"><label>图片<el-input-number v-model="section.image_count" :min="0" :max="3" size="small" @change="saveMediaConfig(section)"/></label><label>表格<el-input-number v-model="section.table_count" :min="0" :max="3" size="small" @change="saveMediaConfig(section)"/></label></div>
            <div class="table-editor"><small>表格管理</small><div v-for="table in sectionTables(chapter,section)" :key="table.id"><el-input v-model="table.title" maxlength="120" @change="saveTable(table,section)"/><button class="danger" @click="removeTable(table)">删除</button></div><button :disabled="sectionTables(chapter,section).length>=3" @click="addTable(chapter,section)">＋ 添加表格</button></div>
          </div>
          <button class="add-row" @click="addSection(chapter)">＋ 新增二级标题</button>
        </article>
        <div class="outline-actions"><button class="add-row" @click="addChapter">＋ 新增一级标题</button><span class="autosave">✓ 所有修改自动保存</span></div>
      </section>
      <section class="panel binding-panel">
        <div class="head"><div><small>IMAGE LIBRARY</small><h2>图片识别与章节确认</h2></div><div><el-button v-if="form.documentMode==='environment'" :loading="searchingWebImages" @click="searchWeb">搜索分析类图片</el-button><el-button :loading="analyzing" @click="analyze">重新分析匹配</el-button></div></div>
        <el-alert title="识别失败的图片会按章节语义归入分析类或设计类待确认列表，不会阻断流程。" type="info" :closable="false"/>
        <el-alert v-if="webSearchReport" :title="webSearchTitle" :description="(webSearchReport.messages||[]).join('；')" :type="webSearchReport.status==='SUCCESS'?'success':'warning'" :closable="false"/>
        <div v-if="flow.materials?.length" class="bindings">
          <article v-for="item in flow.materials" :key="item.id"><img :src="previews[item.id]"/><div class="binding-fields"><el-input v-model="item.display_name" maxlength="100" @change="saveMaterial(item)"/><p><b>{{ item.ai_category||'待分析' }}</b> {{ item.ai_usage }}</p><small>AI 建议：{{ sectionLabel(item.ai_suggested_section) }}</small><el-select v-model="item.user_confirmed_section" placeholder="请选择最终绑定的二级标题"><el-option-group v-for="chapter in flow.chapters" :key="chapter.id" :label="chapter.title"><el-option v-for="section in chapter.sections" :key="section.id" :label="`${section.section_no} ${cleanTitle(section.title)}`" :value="section.id"/></el-option-group></el-select><el-button type="primary" :plain="Boolean(item.is_confirmed)" @click="bind(item)">{{ item.is_confirmed ? '已确认，重新保存' : '确认图片名称与位置' }}</el-button><div v-if="item.source_type==='WEB_SEARCH'||item.source_type==='web_search'" class="web-actions"><el-button @click="previewImage(item)">查看</el-button><el-button :loading="searchingWebImages" @click="replaceWebImage(item)">替换</el-button><span>联网图片仅供项目内确认与生成，不提供下载。</span></div></div></article>
        </div><el-empty v-else description="当前项目没有图片素材"/>
      </section>
      <footer class="panel"><div><strong>确认文档设计</strong><span>正文只读取已确认的大纲、图片和表格；尚有 {{ pendingTaskCount }} 个图片任务待确认。</span></div><el-button type="primary" size="large" :disabled="pendingTaskCount>0" @click="finish">确认并进入正文生成 →</el-button></footer>
    </template>
  </main>
</template>

<script setup>
import { computed, onMounted, onUnmounted, reactive, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { useRouter } from 'vue-router'
import WritingV2Steps from '../../components/WritingV2Steps.vue'
import { addWritingChapter, addWritingSection, addWritingTable, analyzeWritingMaterials, confirmWritingOutline, deleteWritingChapter, deleteWritingMaterial, deleteWritingSection, deleteWritingTable, generateWritingV2Outline, getWritingMaterialContent, getWritingV2Flow, reorderWritingChapters, reorderWritingSections, replaceWritingV2Outline, searchWritingWebImages, updateWritingChapter, updateWritingMaterial, updateWritingSection, updateWritingSectionMediaConfig, updateWritingTable, uploadWritingMaterials } from '../../api/rewrite'
const router=useRouter();const projectId=sessionStorage.getItem('dropai_writing_project_id')||'';const form=reactive({documentMode:'',projectLocation:''});const flow=ref({chapters:[],materials:[]});const previews=reactive({});const generating=ref(false);const analyzing=ref(false);const outlineFiles=ref([]);const imageFiles=ref([]);const replacingOutline=ref(false);const uploadingImages=ref(false);const searchingWebImages=ref(false);const webSearchReport=ref(null)
const modes=[{value:'general',icon:'文',label:'普通纯文字稿',description:'通用论文结构，手动设置每个小节的图片和表格数量'},{value:'environment',icon:'景',label:'环境专业',description:'基址与区位分析，设计方案优先绑定成果图'},{value:'visual_communication',icon:'视',label:'视觉传达专业',description:'视觉系统、应用设计与效果展示专属结构'},{value:'interior_design',icon:'室',label:'室内设计专业',description:'基地调研、空间策略与方案展示专属结构'}]
const outlineReady=computed(()=>Boolean(flow.value.chapters?.length&&form.documentMode));const isGeneral=computed(()=>form.documentMode==='general');const currentMode=computed(()=>modes.find(x=>x.value===form.documentMode)||{label:'未选择'})
const webSearchTitle=computed(()=>{const r=webSearchReport.value||{};return r.status==='SUCCESS'?`联网图片搜索完成：新增 ${r.added||0} 张，候选共 ${r.total||0} 张`:`联网图片搜索未获得新结果（候选共 ${r.total||0} 张）`})
const pendingTaskCount=computed(()=>(flow.value.imageTasks||[]).filter(item=>item.status!=='CONFIRMED').length)
async function load(){if(!projectId){ElMessage.warning('请先完成文献搜索');return router.push('/writing-generator')}flow.value=hydrate(await getWritingV2Flow(projectId));form.documentMode=flow.value.document_mode||'';form.projectLocation=flow.value.project_location||'';await refreshPreviews()}
async function refreshPreviews(){await Promise.all((flow.value.materials||[]).map(async item=>{if(previews[item.id])return;const blob=await getWritingMaterialContent(projectId,item.id);previews[item.id]=URL.createObjectURL(blob)}))}
async function generate(){if(!form.documentMode)return ElMessage.warning('请先选择文档模式');generating.value=true;try{flow.value=hydrate(await generateWritingV2Outline(projectId,form));await refreshPreviews();ElMessage.success('AI 提纲已生成，请编辑并确认')}finally{generating.value=false}}
async function analyze(){analyzing.value=true;try{flow.value=await analyzeWritingMaterials(projectId);await refreshPreviews();ElMessage.success('图片建议绑定已更新')}finally{analyzing.value=false}}
async function saveCount(section){flow.value=await updateWritingSectionMediaConfig(projectId,section.id,{imageCount:section.image_count,tableCount:section.table_count})}
function hydrate(data){for(const chapter of data.chapters||[])for(const section of chapter.sections||[]){try{section.imageRequirements=Array.isArray(section.image_requirements_json)?section.image_requirements_json:JSON.parse(section.image_requirements_json||'[]')}catch{section.imageRequirements=[]}section.newRequirement=''}return data}
async function addRequirement(section){const value=String(section.newRequirement||'').trim();if(value&&!section.imageRequirements.includes(value))section.imageRequirements.push(value);section.newRequirement='';await saveMediaConfig(section)}
async function removeRequirement(section,index){section.imageRequirements.splice(index,1);await saveMediaConfig(section)}
async function saveChapter(chapter){await updateWritingChapter(projectId,chapter.id,{title:chapter.title,chapterType:chapter.chapter_type,targetWordCount:chapter.target_word_count,sectionCount:chapter.sections.length,imageCount:chapter.image_count,tableCount:chapter.table_count,useReferences:chapter.use_references,defaultChartType:chapter.default_chart_type});await refreshFlow()}
async function saveSection(section){await updateWritingSection(projectId,section.id,{title:section.title,targetWordCount:section.target_word_count,imageRequirements:section.imageRequirements});await refreshFlow()}
async function saveMediaConfig(section){flow.value=hydrate(await updateWritingSectionMediaConfig(projectId,section.id,{imageCount:section.image_count,tableCount:section.table_count,imageRequirements:section.imageRequirements}))}
async function replaceOutline(){replacingOutline.value=true;try{flow.value=hydrate(await replaceWritingV2Outline(projectId,outlineFiles.value[0]));outlineFiles.value=[];await refreshPreviews();ElMessage.success('上传目录已完全替换系统模板')}finally{replacingOutline.value=false}}
async function uploadImages(){uploadingImages.value=true;try{await uploadWritingMaterials(projectId,imageFiles.value);imageFiles.value=[];await analyze();await refreshFlow();await refreshPreviews();ElMessage.success('图片已上传并进入确认列表')}finally{uploadingImages.value=false}}
async function searchWeb(){if(!form.projectLocation?.trim())return ElMessage.warning('请先填写项目地址并重新生成环境专业提纲');searchingWebImages.value=true;try{const result=await searchWritingWebImages(projectId);flow.value=hydrate(result);webSearchReport.value=result.webImageSearch||null;await refreshPreviews();if(webSearchReport.value?.status==='SUCCESS')ElMessage.success(`已找到 ${webSearchReport.value.added||0} 张新图片，请逐张确认`);else ElMessage.warning((webSearchReport.value?.messages||['未找到可用联网图片']).join('；'))}finally{searchingWebImages.value=false}}
function previewImage(item){window.open(previews[item.id], '_blank', 'noopener,noreferrer')}
async function replaceWebImage(item){searchingWebImages.value=true;try{await deleteWritingMaterial(projectId,item.id);if(previews[item.id]){URL.revokeObjectURL(previews[item.id]);delete previews[item.id]}flow.value=hydrate(await searchWritingWebImages(projectId));await refreshPreviews();ElMessage.success('已重新搜索并替换联网图片')}finally{searchingWebImages.value=false}}
async function refreshFlow(){flow.value=hydrate(await getWritingV2Flow(projectId))}
async function addChapter(){await addWritingChapter(projectId,{title:'新增章节',sectionCount:1,imageCount:0,tableCount:0});await refreshFlow()}
async function removeChapter(chapter){await deleteWritingChapter(projectId,chapter.id);await refreshFlow()}
async function addSection(chapter){await addWritingSection(projectId,chapter.id,{title:'新增小节',targetWordCount:500});await refreshFlow()}
async function removeSection(section){await deleteWritingSection(projectId,section.id);await refreshFlow()}
async function moveChapter(index,offset){const items=flow.value.chapters;const target=index+offset;if(target<0||target>=items.length)return;[items[index],items[target]]=[items[target],items[index]];await reorderWritingChapters(projectId,items.map(x=>x.id));await refreshFlow()}
async function moveSection(chapter,index,offset){const target=index+offset;if(target<0||target>=chapter.sections.length)return;[chapter.sections[index],chapter.sections[target]]=[chapter.sections[target],chapter.sections[index]];await reorderWritingSections(projectId,chapter.sections.map(x=>x.id));await refreshFlow()}
function sectionTables(chapter,section){return (chapter.tables||[]).filter(table=>(table.user_confirmed_section||table.insert_after_section)===section.id)}
async function addTable(chapter,section){await addWritingTable(projectId,chapter.id,{title:'未命名表格',insertAfterSection:section.id});await refreshFlow()}
async function saveTable(table,section){await updateWritingTable(projectId,table.id,{title:table.title,tableType:table.table_type,sourceType:table.source_type,sourceName:table.source_name,sourceUrl:table.source_url,isSimulated:table.is_simulated,headerJson:table.header_json,rowsJson:table.rows_json,useThreeLineStyle:table.use_three_line_style,note:table.note,insertAfterSection:section.id});await refreshFlow()}
async function removeTable(table){await deleteWritingTable(projectId,table.id);await refreshFlow()}
async function saveMaterial(item){flow.value.materials=await updateWritingMaterial(projectId,item.id,{displayName:item.display_name,userConfirmedChapter:item.user_confirmed_chapter,userConfirmedSection:item.user_confirmed_section,displayOrder:item.display_order||0})}
async function bind(item){if(!item.display_name?.trim())return ElMessage.warning('请先填写图片名称');if(!item.user_confirmed_section)return ElMessage.warning('请选择图片所属二级标题');const section=allSections().find(x=>x.id===item.user_confirmed_section);item.user_confirmed_chapter=section?.chapter_id||'';await saveMaterial(item);item.is_confirmed=1;ElMessage.success('图片名称与章节位置已确认')}
function allSections(){return (flow.value.chapters||[]).flatMap(x=>x.sections||[])}function sectionLabel(id){const s=allSections().find(x=>x.id===id);return s?`${s.section_no} ${cleanTitle(s.title)}`:'暂无建议'}function cleanTitle(title){return String(title||'').replace(/^\d+(\.\d+)?\s*/,'').replace(/^（[一二三四五六七八九十]+）/,'')}function typeName(type){return({analysis:'分析类',design:'设计类',conclusion:'结论',general:'通用'})[type]||'通用'}function strategyName(value){return value==='web_search'?'联网图片':value==='upload'?'用户上传':'无需配图'}async function finish(){try{await confirmWritingOutline(projectId);sessionStorage.setItem('dropai_writing_outline_confirmed','true');sessionStorage.setItem('dropai_writing_v2_ready','true');router.push('/writing-generator/generate')}catch(error){ElMessage.warning(error?.message||'请先确认所有图片和表格')}}
function sectionImageTasks(sectionId){return (flow.value.imageTasks||[]).filter(item=>item.section_id===sectionId)}
function taskStatus(status){return ({PENDING:'待准备',SEARCHING:'搜索中',FOUND:'已找到，待确认',CONFIRMED:'已确认',EMPTY:'未找到',FAILED:'搜索失败'})[status]||status}
onMounted(load);onUnmounted(()=>Object.values(previews).forEach(URL.revokeObjectURL))
</script>

<style scoped>
.outline-page{min-height:100vh;padding:0 5vw 50px;background:#f4f7f6;color:#17211e}.outline-page>nav{min-height:68px;display:grid;grid-template-columns:180px 1fr 180px;align-items:center;border-bottom:1px solid #dce4e1}.brand,.ghost{border:0;background:transparent;cursor:pointer}.brand{justify-self:start;width:36px;height:36px;color:#fff;background:#176b57}.brand span{position:absolute;margin-left:14px;color:#17211e;font-weight:700}.ghost{justify-self:end;color:#176b57}.outline-page>header{max-width:800px;margin:42px auto 25px;text-align:center}.outline-page>header span,.head small{color:#176b57;font-size:12px;letter-spacing:.12em}.outline-page h1{margin:8px;font-size:38px}.outline-page header p,.head>span,footer span{color:#687772}.panel{max-width:1120px;margin:16px auto;padding:24px;border:1px solid #dce4e1;background:#fff}.mode-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.mode-grid button{display:grid;gap:7px;padding:20px;text-align:left;border:1px solid #dce4e1;background:#fff;cursor:pointer}.mode-grid button.selected{border-color:#176b57;box-shadow:inset 0 0 0 1px #176b57;background:#f0f8f5}.mode-grid b{display:grid;place-items:center;width:34px;height:34px;color:#176b57;background:#e5f1ed}.mode-grid small{color:#687772;line-height:1.5}.location{margin-top:20px}.location p{margin-top:-12px;color:#687772;font-size:13px}.generate{width:100%;margin-top:20px}.head,footer{display:flex;align-items:center;justify-content:space-between;gap:18px}.head h2{margin:5px 0}.chapter{margin-top:18px;border:1px solid #e0e7e4}.chapter h3{margin:0;padding:13px 16px;background:#f1f5f3}.section-row{display:flex;justify-content:space-between;gap:16px;padding:13px 16px;border-top:1px solid #e6ebe9}.section-row>div:first-child{display:flex;align-items:center;gap:10px}.section-row small{color:#71807b}.type{padding:3px 7px;border-radius:10px;background:#edf2f0;color:#52645e;font-size:11px}.type.analysis{color:#8a5a12;background:#fff3d9}.type.design{color:#315e9b;background:#eaf2ff}.counts{display:flex;gap:14px}.counts label{display:flex;align-items:center;gap:6px;font-size:13px}.binding-panel .el-alert{margin:16px 0}.bindings{display:grid;gap:12px}.bindings article{display:grid;grid-template-columns:150px 1fr;gap:16px;padding:12px;border:1px solid #e0e7e4}.bindings img{width:150px;height:120px;object-fit:cover;background:#edf2f0}.binding-fields{display:grid;gap:8px}.binding-fields p{margin:0;color:#52645e}.binding-fields small{color:#7b8582}footer div{display:grid;gap:5px}@media(max-width:900px){.outline-page{padding:0 12px 35px}.outline-page>nav{grid-template-columns:60px 1fr}.outline-page>nav>.ghost{display:none}.mode-grid{grid-template-columns:1fr 1fr}.head,footer,.section-row{align-items:stretch;flex-direction:column}.bindings article{grid-template-columns:100px 1fr}.bindings img{width:100px;height:100px}}@media(max-width:560px){.mode-grid{grid-template-columns:1fr}.counts{flex-direction:column}}
.asset-tools{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-bottom:24px}.asset-tools>div{padding:16px;border:1px solid #dce4e1;background:#f8faf9}.asset-tools h3{margin:0}.asset-tools p{color:#687772;font-size:13px}.asset-tools .el-button{margin-top:8px}.chapter-editor,.section-title,.image-requirements,.outline-actions{display:flex;align-items:center;gap:8px}.chapter-editor{padding:13px 16px;background:#f1f5f3}.chapter-editor .el-input,.section-title .el-input{flex:1}.section-editor{padding:13px 16px;border-top:1px solid #e6ebe9}.image-requirements{flex-wrap:wrap;margin-top:10px}.image-requirements .el-input{max-width:260px}.chapter-editor button,.section-title button,.image-requirements button,.table-editor button,.add-row{border:1px solid #cdd8d4;background:#fff;padding:6px 9px;cursor:pointer}.danger{color:#b64b4b}.add-row{margin:12px 16px}.outline-actions{justify-content:space-between;margin-top:16px}.autosave{color:#176b57}.table-editor{display:grid;gap:8px;margin-top:12px;padding-top:12px;border-top:1px dashed #dce4e1}.table-editor>div{display:flex;gap:8px}.table-editor>button{justify-self:start}.web-actions{display:flex;align-items:center;gap:8px}.web-actions span{color:#7b8582;font-size:12px}@media(max-width:900px){.asset-tools{grid-template-columns:1fr}.chapter-editor,.section-title{align-items:stretch;flex-wrap:wrap}.chapter-editor .el-input,.section-title .el-input{flex-basis:70%}}
.image-tasks{display:flex;align-items:center;flex-wrap:wrap;gap:8px;margin-top:10px}.image-tasks>small{color:#687772}.task{display:flex;gap:6px;padding:5px 9px;border-radius:14px;background:#f3f5f4;color:#687772;font-size:12px}.task.found,.task.searching{background:#fff4d9;color:#8a5a12}.task.confirmed{background:#e6f5ef;color:#176b57}.task.empty,.task.failed{background:#fdecec;color:#a63f3f}
</style>
