package com.dropai.rewrite.service.diagram;

import com.dropai.rewrite.service.DiagramService;
import com.dropai.rewrite.service.diagram.DiagramIr.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.function.Consumer;

@Service
public class DiagramGenerationService {
    private static final Logger log=LoggerFactory.getLogger(DiagramGenerationService.class);
    private final DiagramDslCodec codec;private final DiagramPromptFactory prompts;private final DoubaoDiagramClient client;private final DiagramRuleEngine rules;private final SqlSchemaExtractor sqlExtractor;private final SqlRelationResolver sqlResolver;private final DiagramService diagrams;private final ObjectMapper mapper;
    private final Set<String> active=ConcurrentHashMap.newKeySet();
    public DiagramGenerationService(DiagramDslCodec codec,DiagramPromptFactory prompts,DoubaoDiagramClient client,DiagramRuleEngine rules,SqlSchemaExtractor sqlExtractor,SqlRelationResolver sqlResolver,DiagramService diagrams,ObjectMapper mapper){this.codec=codec;this.prompts=prompts;this.client=client;this.rules=rules;this.sqlExtractor=sqlExtractor;this.sqlResolver=sqlResolver;this.diagrams=diagrams;this.mapper=mapper;}
    public Done generate(long userId,Request request,Consumer<Event> events){String requestId=blank(request.requestId())?UUID.randomUUID().toString():request.requestId();String lock=userId+":"+Objects.toString(request.conversationId(),"default");if(!active.add(lock))throw new DiagramGenerationException("GENERATION_ALREADY_RUNNING","当前编辑器已有生成任务，请勿重复提交。");long started=System.nanoTime();String code="SUCCESS";try{
        String current=Objects.toString(request.currentDsl(),"");String actualHash=hash(current);if(!blank(request.baseDslHash())&&!request.baseDslHash().equals(actualHash))throw new DiagramGenerationException("STALE_GENERATION_RESULT","当前代码已变化，旧生成任务已取消。");
        DiagramType type=type(request,current);events.accept(new Event("accepted",requestId,"任务已接受",null));events.accept(new Event("analyzing",requestId,"正在理解图形需求",null));DiagramIr currentIr=current.isBlank()?null:codec.parse(current);DiagramIr raw;boolean modelCalled;
        long modelStart=System.nanoTime();DoubaoDiagramClient.ModelResult modelResult=null;if(!blank(request.sqlText())){if(type!=DiagramType.ER_DIAGRAM)throw new DiagramGenerationException("SQL_PARSE_FAILED","SQL文件只能生成ER图，原图已恢复。");raw=sqlResolver.resolve(sqlExtractor.extract(request.sqlText()),blank(request.instruction())?"数据库ER图":request.instruction());modelCalled=false;}else{DiagramPromptFactory.Prompt prompt=prompts.build(type,request.instruction(),currentIr);modelCalled=true;modelResult=client.generate(type,prompt,count->events.accept(new Event("model_delta",requestId,"正在整理节点关系",new Progress(count))));raw=parseModel(type,modelResult.json());}
        long modelTotal=(System.nanoTime()-modelStart)/1_000_000;events.accept(new Event("normalizing",requestId,"正在规范分支关系",null));long n=System.nanoTime();DiagramIr normalized=rules.normalize(raw);long normalizeMs=(System.nanoTime()-n)/1_000_000;events.accept(new Event("compiling",requestId,"正在生成 DSL",null));long c=System.nanoTime();String dsl=codec.compile(normalized);long compileMs=(System.nanoTime()-c)/1_000_000;events.accept(new Event("validating",requestId,"正在检查图形代码",null));long v=System.nanoTime();var validation=diagrams.validate(dsl);if(!validation.path("valid").asBoolean())throw new DiagramGenerationException("DSL_VALIDATION_FAILED","本地生成的DSL未通过现有绘图器校验，原图已恢复。");long validateMs=(System.nanoTime()-v)/1_000_000;
        Metrics metrics=new Metrics(modelResult==null?0:modelResult.firstByteMs(),modelResult==null?modelTotal:modelResult.totalMs(),normalizeMs,compileMs,validateMs,dsl.length(),modelCalled?1:0);Done done=new Done(requestId,request.generationId(),actualHash,type,dsl,warnings(normalized),metrics);events.accept(new Event("done",requestId,"生成完成",done));log(requestId,type,request,currentIr,modelCalled,metrics,"SUCCESS",started);return done;
    }catch(DiagramGenerationException e){code=e.code();events.accept(new Event("error",requestId,e.getMessage(),new ErrorData(e.code(),e.getMessage(),e.retryable())));throw e;}catch(Exception e){code="INVALID_MODEL_JSON";DiagramGenerationException x=new DiagramGenerationException(code,"豆包返回的DiagramIR无法解析，原图已恢复。",false,e);events.accept(new Event("error",requestId,x.getMessage(),new ErrorData(x.code(),x.getMessage(),false)));throw x;}finally{active.remove(lock);if(!"SUCCESS".equals(code))log.info("diagram generation requestId={} resultCode={}",requestId,code);}}
    private DiagramIr parseModel(DiagramType type,String json){try{return switch(type){case FLOWCHART->mapper.readValue(json,FlowchartIr.class);case ER_DIAGRAM->mapper.readValue(json,ErDiagramIr.class);case FUNCTION_MODULE->mapper.readValue(json,FunctionModuleIr.class);case ARCHITECTURE->mapper.readValue(json,ArchitectureIr.class);case USE_CASE->mapper.readValue(json,UseCaseIr.class);case BLOCK_DIAGRAM->mapper.readValue(json,BlockDiagramIr.class);case SEQUENCE_DIAGRAM->mapper.readValue(json,SequenceDiagramIr.class);};}catch(Exception e){throw new DiagramGenerationException("INVALID_MODEL_JSON","豆包返回的内容不是合法DiagramIR JSON，原图已恢复。",false,e);}}
    private DiagramType type(Request r,String current){if(!blank(r.diagramType())){String v=r.diagramType().trim();if(v.startsWith("@"))return codec.fromHeader(v);try{return DiagramType.valueOf(v.toUpperCase());}catch(Exception ignored){}}if(!current.isBlank())return codec.parse(current).diagramType();String v=Objects.toString(r.instruction(),"").toLowerCase();if(v.contains("er图")||v.contains("实体关系")||!blank(r.sqlText()))return DiagramType.ER_DIAGRAM;if(v.contains("流程"))return DiagramType.FLOWCHART;if(v.contains("功能模块"))return DiagramType.FUNCTION_MODULE;if(v.contains("架构"))return DiagramType.ARCHITECTURE;if(v.contains("用例"))return DiagramType.USE_CASE;if(v.contains("框图")||v.contains("方框图"))return DiagramType.BLOCK_DIAGRAM;if(v.contains("时序")||v.contains("顺序图"))return DiagramType.SEQUENCE_DIAGRAM;throw new DiagramGenerationException("DIAGRAM_TYPE_REQUIRED","请明确说明需要生成的图形类型，原图已恢复。");}
    private List<Warning> warnings(DiagramIr ir){if(ir instanceof FlowchartIr x)return safe(x.warnings());if(ir instanceof ErDiagramIr x)return safe(x.warnings());if(ir instanceof FunctionModuleIr x)return safe(x.warnings());if(ir instanceof ArchitectureIr x)return safe(x.warnings());if(ir instanceof UseCaseIr x)return safe(x.warnings());if(ir instanceof BlockDiagramIr x)return safe(x.warnings());if(ir instanceof SequenceDiagramIr x)return safe(x.warnings());return List.of();}
    private void log(String id,DiagramType type,Request r,DiagramIr current,boolean called,Metrics m,String result,long started){int[] count=count(current);log.info("diagram generation requestId={} diagramType={} mode={} inputChars={} existingNodes={} existingEdges={} modelCalled={} firstByteMs={} modelTotalMs={} normalizeMs={} compileMs={} validateMs={} outputDslLength={} resultCode={} totalMs={}",id,type,blank(r.sqlText())?(blank(r.currentDsl())?"TEXT":"EXISTING_DSL"):"SQL",Objects.toString(r.instruction(),"").length()+Objects.toString(r.sqlText(),"").length(),count[0],count[1],called,m.firstByteMs(),m.modelTotalMs(),m.normalizeMs(),m.compileMs(),m.validateMs(),m.outputDslLength(),result,(System.nanoTime()-started)/1_000_000);}
    private int[] count(DiagramIr ir){if(ir==null)return new int[]{0,0};if(ir instanceof FlowchartIr x)return new int[]{safe(x.nodes()).size(),safe(x.edges()).size()};if(ir instanceof ErDiagramIr x)return new int[]{safe(x.entities()).size(),safe(x.relations()).size()};if(ir instanceof FunctionModuleIr x)return new int[]{safe(x.modules()).size(),0};if(ir instanceof ArchitectureIr x)return new int[]{safe(x.layers()).size(),safe(x.dependencies()).size()};if(ir instanceof UseCaseIr x)return new int[]{safe(x.actors()).size()+safe(x.useCases()).size(),safe(x.relations()).size()};if(ir instanceof BlockDiagramIr x)return new int[]{safe(x.blocks()).size(),safe(x.edges()).size()};if(ir instanceof SequenceDiagramIr x)return new int[]{safe(x.participants()).size(),safe(x.messages()).size()};return new int[]{0,0};}
    public static String hash(String value){try{byte[] d=MessageDigest.getInstance("SHA-256").digest(Objects.toString(value,"").replace("\r\n","\n").getBytes(StandardCharsets.UTF_8));return java.util.HexFormat.of().formatHex(d);}catch(Exception e){throw new IllegalStateException(e);}}
    private static boolean blank(String s){return s==null||s.isBlank();}private static <T> List<T> safe(List<T> v){return v==null?List.of():v;}
    public record Request(String requestId,String generationId,String conversationId,String baseDslHash,String diagramType,String instruction,String currentDsl,String sqlText){}
    public record Event(String event,String requestId,String message,Object data){} public record Progress(int charactersReceived){} public record ErrorData(String code,String message,boolean retryable){}
    public record Metrics(long firstByteMs,long modelTotalMs,long normalizeMs,long compileMs,long validateMs,int outputDslLength,int modelCalls){}
    public record Done(String requestId,String generationId,String baseDslHash,DiagramType diagramType,String dsl,List<Warning> warnings,Metrics metrics){}
}
