package com.dropai.rewrite.service.diagram;

import com.dropai.rewrite.service.diagram.DiagramIr.*;
import org.springframework.stereotype.Component;
import java.util.*;
import java.util.regex.*;

@Component
public class DiagramDslCodec {
    public DiagramIr parse(String dsl){if(dsl==null||dsl.isBlank())return null;List<String> lines=dsl.replace("\uFEFF","").replace("\r","").lines().map(String::trim).filter(s->!s.isEmpty()).toList();if(lines.isEmpty())return null;DiagramType type=fromHeader(lines.get(0));return switch(type){case FLOWCHART->parseFlow(lines);case ER_DIAGRAM->parseEr(lines);case FUNCTION_MODULE->parseFunction(lines);case ARCHITECTURE->parseArchitecture(lines);case USE_CASE->parseUseCase(lines);case BLOCK_DIAGRAM->parseBlock(lines);case SEQUENCE_DIAGRAM->parseSequence(lines);};}
    public String compile(DiagramIr ir){if(ir instanceof FlowchartIr x)return new FlowchartDslCompiler().compile(x);if(ir instanceof ErDiagramIr x)return new ErDiagramDslCompiler().compile(x);if(ir instanceof FunctionModuleIr x)return new FunctionModuleDslCompiler().compile(x);if(ir instanceof ArchitectureIr x)return new ArchitectureDslCompiler().compile(x);if(ir instanceof UseCaseIr x)return new UseCaseDslCompiler().compile(x);if(ir instanceof BlockDiagramIr x)return new BlockDiagramDslCompiler().compile(x);if(ir instanceof SequenceDiagramIr x)return new SequenceDiagramDslCompiler().compile(x);throw new DiagramGenerationException("DSL_COMPILE_FAILED","不支持的DiagramIR类型");}
    public DiagramType fromHeader(String h){return switch(h){case "@FunctionModule"->DiagramType.FUNCTION_MODULE;case "@Flowchart"->DiagramType.FLOWCHART;case "@ERDiagram"->DiagramType.ER_DIAGRAM;case "@ArchitectureDiagram"->DiagramType.ARCHITECTURE;case "@UseCaseDiagram"->DiagramType.USE_CASE;case "@BlockDiagram"->DiagramType.BLOCK_DIAGRAM;case "@SequenceDiagram"->DiagramType.SEQUENCE_DIAGRAM;default->throw new DiagramGenerationException("DIAGRAM_TYPE_REQUIRED","请明确选择七种图形类型之一。");};}
    public String header(DiagramType t){return switch(t){case FUNCTION_MODULE->"@FunctionModule";case FLOWCHART->"@Flowchart";case ER_DIAGRAM->"@ERDiagram";case ARCHITECTURE->"@ArchitectureDiagram";case USE_CASE->"@UseCaseDiagram";case BLOCK_DIAGRAM->"@BlockDiagram";case SEQUENCE_DIAGRAM->"@SequenceDiagram";};}
    private FlowchartIr parseFlow(List<String> l){String title=title(l,"流程图");List<FlowNode> ns=new ArrayList<>();List<Edge> es=new ArrayList<>();String sec="";for(int i=1;i<l.size();i++){String s=l.get(i);if(s.equals("[节点]")||s.equals("[连接]")){sec=s;continue;}if(s.startsWith("标题"))continue;if(sec.equals("[节点]")){String[] p=s.split("\\|",3);if(p.length==3)ns.add(new FlowNode(p[0],enumValue(FlowNodeKind.class,p[1]),p[2]));}else if(sec.equals("[连接]")){Matcher m=Pattern.compile("([^|>-]+)->([^|]+?)(?:\\|(.+))?$").matcher(s);if(m.find())es.add(new Edge("e"+(es.size()+1),m.group(1),m.group(2),"normal",Objects.toString(m.group(3),""),es.size()+1));}}return new FlowchartIr("1.0",DiagramType.FLOWCHART,title,ns,es,List.of());}
    private ErDiagramIr parseEr(List<String> l){String title=title(l,"ER图");List<ErEntity> entities=new ArrayList<>();List<ErRelation> rels=new ArrayList<>();for(String s:l){Matcher em=Pattern.compile("^实体[：:]([^|｜]+)[|｜](.+)$").matcher(s);if(em.find()){List<ErAttribute> attrs=new ArrayList<>();for(String a:em.group(2).split("[,，]")){String n=a.trim();boolean pk=n.endsWith("*");if(pk)n=n.substring(0,n.length()-1);attrs.add(new ErAttribute(slug(n),n,"",pk,false,false,true));}entities.add(new ErEntity(slug(em.group(1)),em.group(1).trim(),attrs,false));}Matcher rm=Pattern.compile("^关系[：:]([^|]+)\\|([^|]+)\\|([^|]+)\\|([1mMnN])\\|([1mMnN])$").matcher(s);if(rm.find())rels.add(new ErRelation("r"+(rels.size()+1),slug(rm.group(1)),"",slug(rm.group(2)),"",card(rm.group(4)),card(rm.group(5)),rm.group(3),RelationSource.USER,1d));}return new ErDiagramIr("1.0",DiagramType.ER_DIAGRAM,title,entities,rels,List.of(),List.of());}
    private FunctionModuleIr parseFunction(List<String> l){String title="功能模块图";List<ModuleNode> modules=new ArrayList<>();ModuleNode pending=null;for(String s:l){if(s.matches("^系统[：:].+"))title=s.replaceFirst("^系统[：:]","").trim();else if(s.matches("^模块[：:].+")){pending=new ModuleNode("m"+(modules.size()+1),s.replaceFirst("^模块[：:]","").trim(),null,new ArrayList<>());modules.add(pending);}else if(s.matches("^功能[：:].+")&&pending!=null){List<String> f=Arrays.stream(s.replaceFirst("^功能[：:]","").split("[,，]")).map(String::trim).filter(x->!x.isEmpty()).toList();modules.set(modules.size()-1,new ModuleNode(pending.id(),pending.name(),pending.parentId(),f));pending=modules.get(modules.size()-1);}}return new FunctionModuleIr("1.0",DiagramType.FUNCTION_MODULE,title,modules,List.of());}
    private ArchitectureIr parseArchitecture(List<String> l){String title=title(l,"系统架构图");List<ArchitectureLayer> layers=new ArrayList<>();String layer=null;for(String s:l){if(s.matches("^层[：:].+"))layer=s.replaceFirst("^层[：:]","").trim();else if(s.matches("^组件[：:].+")&&layer!=null){List<String> cs=Arrays.stream(s.replaceFirst("^组件[：:]","").split("[,，]")).map(String::trim).toList();layers.add(new ArchitectureLayer("l"+(layers.size()+1),layer,cs));layer=null;}}return new ArchitectureIr("1.0",DiagramType.ARCHITECTURE,title,layers,List.of(),List.of());}
    private UseCaseIr parseUseCase(List<String> l){String title=title(l,"用例图"),sec="",sid="S1",sname=title;List<Actor> actors=new ArrayList<>();List<UseCase> cases=new ArrayList<>();List<UseCaseRelation> rels=new ArrayList<>();for(String s:l){if(s.startsWith("[")){sec=s;continue;}if(s.startsWith("标题"))continue;String[] p=s.split("\\|");if(sec.equals("[系统]")&&p.length==2){sid=p[0];sname=p[1];}else if(sec.equals("[参与者]")&&p.length==2)actors.add(new Actor(p[0],p[1],null));else if(sec.equals("[用例]")&&p.length==3)cases.add(new UseCase(p[0],p[1],p[2]));else if(sec.equals("[关联]")&&s.contains("->")){String[] q=s.split("->");rels.add(new UseCaseRelation("r"+(rels.size()+1),q[0],q[1],UseCaseRelationKind.ASSOCIATION));}else if(sec.equals("[用例关系]")&&p.length==2){String[] q=p[0].split("->");rels.add(new UseCaseRelation("r"+(rels.size()+1),q[0],q[1],enumValue(UseCaseRelationKind.class,p[1])));}}return new UseCaseIr("1.0",DiagramType.USE_CASE,title,sid,sname,actors,cases,rels,List.of());}
    private BlockDiagramIr parseBlock(List<String> l){String title=title(l,"系统框图"),sec="";List<Block> blocks=new ArrayList<>();List<Edge> edges=new ArrayList<>();for(String s:l){if(s.startsWith("[")){sec=s;continue;}if(s.startsWith("标题"))continue;if(sec.equals("[节点]")){String[] p=s.split("\\|",3);if(p.length==3)blocks.add(new Block(p[0],p[1].toUpperCase(),p[2]));}else if(sec.equals("[连接]")&&s.contains("->")){String[] p=s.split("->");edges.add(new Edge("e"+(edges.size()+1),p[0],p[1],"signal","",edges.size()+1));}}return new BlockDiagramIr("1.0",DiagramType.BLOCK_DIAGRAM,title,blocks,edges,List.of());}
    private SequenceDiagramIr parseSequence(List<String> l){String title=title(l,"时序图"),sec="";List<Participant> ps=new ArrayList<>();List<Message> ms=new ArrayList<>();for(String s:l){if(s.startsWith("[")){sec=s;continue;}if(s.startsWith("标题"))continue;if(sec.equals("[参与者]")){String[] p=s.split("\\|",3);if(p.length==3)ps.add(new Participant(p[0],p[1].toUpperCase(),p[2]));}else if(sec.equals("[消息]")){Matcher m=Pattern.compile("^([^->]+)(-->|->)([^|]+)\\|(.+)$").matcher(s);if(m.find())ms.add(new Message("m"+(ms.size()+1),m.group(1),m.group(3),m.group(2).equals("-->")?MessageKind.RETURN:MessageKind.CALL,m.group(4),ms.size()+1));}}return new SequenceDiagramIr("1.0",DiagramType.SEQUENCE_DIAGRAM,title,ps,ms,List.of());}
    private String title(List<String> lines,String fallback){return lines.stream().filter(s->s.matches("^标题[：:].+")).findFirst().map(s->s.replaceFirst("^标题[：:]","").trim()).orElse(fallback);}
    private static String slug(String s){String v=s.trim().replaceAll("[^A-Za-z0-9_\\-\\u4e00-\\u9fff]","");return v.isEmpty()?"item":v;}
    private static String card(String s){return s.equals("1")?"1":s.equalsIgnoreCase("m")?"M":"N";} private static <E extends Enum<E>> E enumValue(Class<E> c,String s){return Enum.valueOf(c,s.trim().toUpperCase());}
    interface Compiler<T extends DiagramIr>{String compile(T ir);}
    public static final class FlowchartDslCompiler implements Compiler<FlowchartIr>{public String compile(FlowchartIr x){StringBuilder b=new StringBuilder("@Flowchart\n标题：").append(x.title()).append("\n\n[节点]\n");x.nodes().forEach(n->b.append(n.id()).append('|').append(n.kind().name().toLowerCase()).append('|').append(n.text()).append('\n'));b.append("\n[连接]\n");x.edges().stream().sorted(Comparator.comparing(e->Objects.requireNonNullElse(e.order(),0))).forEach(e->b.append(e.from()).append("->").append(e.to()).append(blank(e.label())?"":"|"+e.label()).append('\n'));return b.toString().trim();}}
    public static final class ErDiagramDslCompiler implements Compiler<ErDiagramIr>{public String compile(ErDiagramIr x){StringBuilder b=new StringBuilder("@ERDiagram\n标题：").append(x.title()).append("\n\n[实体]\n");for(ErEntity e:x.entities()){boolean chinese=e.name()!=null&&e.name().codePoints().anyMatch(c->Character.UnicodeScript.of(c)==Character.UnicodeScript.HAN);b.append(chinese?"实体：":"").append(e.name()).append(chinese?'|':'：');for(int i=0;i<e.attributes().size();i++){ErAttribute a=e.attributes().get(i);if(i>0)b.append('，');b.append(a.name()).append(a.primaryKey()?"*":"");}b.append('\n');}b.append("\n[关系]\n");for(ErRelation r:x.relations()){String a=name(x,r.sourceEntityId()),z=name(x,r.targetEntityId());b.append("关系：").append(a).append('|').append(z).append('|').append(blank(r.name())?"关联":r.name()).append('|').append(r.sourceCardinality().toLowerCase()).append('|').append(r.targetCardinality().toLowerCase()).append('\n');}return b.toString().trim();}private String name(ErDiagramIr x,String id){return x.entities().stream().filter(e->e.id().equals(id)).findFirst().map(ErEntity::name).orElse(id);}}
    public static final class FunctionModuleDslCompiler implements Compiler<FunctionModuleIr>{public String compile(FunctionModuleIr x){StringBuilder b=new StringBuilder("@FunctionModule\n系统：").append(x.title()).append('\n');for(ModuleNode m:x.modules()){b.append("\n模块：").append(m.name()).append("\n功能：").append(String.join("，",m.functions())).append('\n');}return b.toString().trim();}}
    public static final class ArchitectureDslCompiler implements Compiler<ArchitectureIr>{public String compile(ArchitectureIr x){StringBuilder b=new StringBuilder("@ArchitectureDiagram\n标题：").append(x.title()).append('\n');for(ArchitectureLayer l:x.layers())b.append("\n层：").append(l.name()).append("\n组件：").append(String.join("，",l.components())).append('\n');return b.toString().trim();}}
    public static final class UseCaseDslCompiler implements Compiler<UseCaseIr>{public String compile(UseCaseIr x){StringBuilder b=new StringBuilder("@UseCaseDiagram\n标题：").append(x.title()).append("\n\n[系统]\n").append(x.systemId()).append('|').append(x.systemName()).append("\n\n[参与者]\n");x.actors().forEach(a->b.append(a.id()).append('|').append(a.name()).append('\n'));b.append("\n[用例]\n");x.useCases().forEach(u->b.append(u.id()).append('|').append(u.systemId()).append('|').append(u.name()).append('\n'));b.append("\n[关联]\n");x.relations().stream().filter(r->r.kind()==UseCaseRelationKind.ASSOCIATION).forEach(r->b.append(r.from()).append("->").append(r.to()).append('\n'));List<UseCaseRelation> special=x.relations().stream().filter(r->r.kind()==UseCaseRelationKind.INCLUDE||r.kind()==UseCaseRelationKind.EXTEND).toList();if(!special.isEmpty()){b.append("\n[用例关系]\n");special.forEach(r->b.append(r.from()).append("->").append(r.to()).append('|').append(r.kind().name().toLowerCase()).append('\n'));}return b.toString().trim();}}
    public static final class BlockDiagramDslCompiler implements Compiler<BlockDiagramIr>{public String compile(BlockDiagramIr x){StringBuilder b=new StringBuilder("@BlockDiagram\n标题：").append(x.title()).append("\n\n[节点]\n");x.blocks().forEach(n->b.append(n.id()).append('|').append(n.kind().toLowerCase()).append('|').append(n.text()).append('\n'));b.append("\n[连接]\n");x.edges().forEach(e->b.append(e.from()).append("->").append(e.to()).append('\n'));return b.toString().trim();}}
    public static final class SequenceDiagramDslCompiler implements Compiler<SequenceDiagramIr>{public String compile(SequenceDiagramIr x){StringBuilder b=new StringBuilder("@SequenceDiagram\n标题：").append(x.title()).append("\n\n[参与者]\n");x.participants().forEach(p->b.append(p.id()).append('|').append(p.kind().toLowerCase()).append('|').append(p.name()).append('\n'));b.append("\n[消息]\n");x.messages().stream().sorted(Comparator.comparing(m->Objects.requireNonNullElse(m.order(),0))).limit(8).forEach(m->b.append(m.from()).append(m.kind()==MessageKind.RETURN?"-->":"->").append(m.to()).append('|').append(m.text()).append('\n'));return b.toString().trim();}}
    private static boolean blank(String s){return s==null||s.isBlank();}
}
