package com.dropai.rewrite.service.diagram;

import com.dropai.rewrite.service.diagram.DiagramIr.*;
import org.springframework.stereotype.Component;
import java.util.*;
import java.util.function.Function;

@Component
public class DiagramRuleEngine {
    public DiagramIr normalize(DiagramIr ir){if(ir==null)throw invalid("模型未返回DiagramIR");if(ir instanceof FlowchartIr x)return new FlowchartRuleEngine().normalize(x);if(ir instanceof ErDiagramIr x)return new ErDiagramRuleEngine().normalize(x);if(ir instanceof FunctionModuleIr x)return new FunctionModuleRuleEngine().normalize(x);if(ir instanceof ArchitectureIr x)return new ArchitectureRuleEngine().normalize(x);if(ir instanceof UseCaseIr x)return new UseCaseRuleEngine().normalize(x);if(ir instanceof BlockDiagramIr x)return new BlockDiagramRuleEngine().normalize(x);if(ir instanceof SequenceDiagramIr x)return new SequenceDiagramRuleEngine().normalize(x);throw invalid("不支持的DiagramIR类型");}
    interface Rule<T extends DiagramIr>{T normalize(T value);}
    static final class FlowchartRuleEngine implements Rule<FlowchartIr>{public FlowchartIr normalize(FlowchartIr x){List<FlowNode> nodes=unique(x.nodes(),FlowNode::id);if(nodes.isEmpty())throw invalid("流程图没有节点");Map<String,FlowNode> by=index(nodes,FlowNode::id);List<Edge> edges=edges(x.edges(),by.keySet());long starts=nodes.stream().filter(n->n.kind()==FlowNodeKind.START).count();if(starts!=1)throw invalid("流程图必须有且只有一个开始节点");Set<String> outgoing=new HashSet<>();Map<String,Set<String>> labels=new HashMap<>();Map<String,Integer> outCounts=new HashMap<>();for(Edge e:edges){outgoing.add(e.from());outCounts.merge(e.from(),1,Integer::sum);if(by.get(e.from()).kind()==FlowNodeKind.DECISION){if(blank(e.label()))throw invalid("判断节点的每个分支必须有标签");if(!labels.computeIfAbsent(e.from(),k->new HashSet<>()).add(e.label()))throw invalid("判断节点分支标签不能重复");}}for(FlowNode n:nodes){if(n.kind()==FlowNodeKind.DECISION){int count=outCounts.getOrDefault(n.id(),0);if(labels.getOrDefault(n.id(),Set.of()).size()<2)throw invalid("判断节点至少需要两个不同分支");if(count>2)throw invalid("判断节点最多只能有两个分支，三档及以上状态请合并为处理节点："+n.text());}if(n.kind()!=FlowNodeKind.END&&!outgoing.contains(n.id()))throw invalid("存在没有后续关系的节点："+n.text());}return new FlowchartIr("1.0",DiagramType.FLOWCHART,cleanTitle(x.title(),"流程图"),nodes,edges,warnings(x.warnings()));}}
    static final class ErDiagramRuleEngine implements Rule<ErDiagramIr>{public ErDiagramIr normalize(ErDiagramIr x){List<ErEntity> entities=unique(x.entities(),ErEntity::id);Map<String,ErEntity> by=index(entities,ErEntity::id);List<ErRelation> rels=new ArrayList<>();Set<String> seen=new HashSet<>();for(ErRelation r:safe(x.relations())){if(!by.containsKey(r.sourceEntityId())||!by.containsKey(r.targetEntityId()))throw invalid("ER关系引用不存在实体");String key=r.sourceEntityId()+">"+r.targetEntityId()+":"+r.name();if(seen.add(key))rels.add(new ErRelation(id(r.id(),"r",rels.size()+1),r.sourceEntityId(),nz(r.sourceField()),r.targetEntityId(),nz(r.targetField()),card(r.sourceCardinality()),card(r.targetCardinality()),blank(r.name())?"关联":r.name(),r.source()==null?RelationSource.USER:r.source(),r.confidence()==null?1:r.confidence()));}List<String> core=safe(x.coreEntityIds()).stream().filter(by::containsKey).distinct().toList();return new ErDiagramIr("1.0",DiagramType.ER_DIAGRAM,cleanTitle(x.title(),"ER图"),entities,rels,core,warnings(x.warnings()));}}
    static final class FunctionModuleRuleEngine implements Rule<FunctionModuleIr>{public FunctionModuleIr normalize(FunctionModuleIr x){List<ModuleNode> ms=unique(x.modules(),ModuleNode::id);Set<String> ids=new HashSet<>();ms.forEach(m->ids.add(m.id()));for(ModuleNode m:ms)if(m.parentId()!=null&&!ids.contains(m.parentId()))throw invalid("模块引用不存在的父模块");return new FunctionModuleIr("1.0",DiagramType.FUNCTION_MODULE,cleanTitle(x.title(),"功能模块图"),ms,warnings(x.warnings()));}}
    static final class ArchitectureRuleEngine implements Rule<ArchitectureIr>{public ArchitectureIr normalize(ArchitectureIr x){List<ArchitectureLayer> layers=unique(x.layers(),ArchitectureLayer::id);if(layers.size()<2)throw invalid("架构图至少需要两个层");return new ArchitectureIr("1.0",DiagramType.ARCHITECTURE,cleanTitle(x.title(),"系统架构图"),layers,List.of(),warnings(x.warnings()));}}
    static final class UseCaseRuleEngine implements Rule<UseCaseIr>{public UseCaseIr normalize(UseCaseIr x){List<Actor> actors=unique(x.actors(),Actor::id);List<UseCase> cases=unique(x.useCases(),UseCase::id);Set<String> all=new HashSet<>();actors.forEach(a->all.add(a.id()));cases.forEach(u->all.add(u.id()));List<UseCaseRelation> rels=new ArrayList<>();Set<String> seen=new HashSet<>();for(UseCaseRelation r:safe(x.relations())){if(!all.contains(r.from())||!all.contains(r.to()))throw invalid("用例关系引用不存在对象");String key=r.from()+">"+r.to()+":"+r.kind();if(seen.add(key))rels.add(new UseCaseRelation(id(r.id(),"r",rels.size()+1),r.from(),r.to(),r.kind()==null?UseCaseRelationKind.ASSOCIATION:r.kind()));}return new UseCaseIr("1.0",DiagramType.USE_CASE,cleanTitle(x.title(),"用例图"),id(x.systemId(),"S",1),cleanTitle(x.systemName(),x.title()),actors,cases,rels,warnings(x.warnings()));}}
    static final class BlockDiagramRuleEngine implements Rule<BlockDiagramIr>{public BlockDiagramIr normalize(BlockDiagramIr x){List<Block> blocks=unique(x.blocks(),Block::id);Map<String,Block> by=index(blocks,Block::id);return new BlockDiagramIr("1.0",DiagramType.BLOCK_DIAGRAM,cleanTitle(x.title(),"系统框图"),blocks,edges(x.edges(),by.keySet()),warnings(x.warnings()));}}
    static final class SequenceDiagramRuleEngine implements Rule<SequenceDiagramIr>{public SequenceDiagramIr normalize(SequenceDiagramIr x){List<Participant> ps=unique(x.participants(),Participant::id);Map<String,Participant> by=index(ps,Participant::id);List<Message> ms=new ArrayList<>();int order=0;for(Message m:safe(x.messages())){if(!by.containsKey(m.from())||!by.containsKey(m.to()))throw invalid("时序消息引用不存在参与者");if(ms.size()>=8)break;ms.add(new Message(id(m.id(),"m",++order),m.from(),m.to(),m.kind()==null?MessageKind.CALL:m.kind(),m.text(),order));}if(ps.size()<2||ps.size()>6)throw invalid("时序图参与者数量必须为2至6个");if(ms.isEmpty())throw invalid("时序图至少需要一条消息");return new SequenceDiagramIr("1.0",DiagramType.SEQUENCE_DIAGRAM,cleanTitle(x.title(),"时序图"),ps,ms,warnings(x.warnings()));}}
    private static List<Edge> edges(List<Edge> input,Set<String> ids){List<Edge> out=new ArrayList<>();Set<String> seen=new HashSet<>();int order=0;for(Edge e:safe(input)){if(!ids.contains(e.from())||!ids.contains(e.to()))throw invalid("关系引用不存在节点："+e.from()+" -> "+e.to());String key=e.from()+">"+e.to()+":"+nz(e.label());if(seen.add(key))out.add(new Edge(id(e.id(),"e",++order),e.from(),e.to(),nz(e.kind()),nz(e.label()),order));}return out;}
    private static <T> List<T> unique(List<T> values,Function<T,String> id){List<T> out=new ArrayList<>();Set<String> seen=new HashSet<>();for(T v:safe(values)){String key=id.apply(v);if(blank(key)||!seen.add(key))throw invalid("存在缺失或重复ID");out.add(v);}return out;}
    private static <T> Map<String,T> index(List<T> values,Function<T,String> id){Map<String,T> m=new LinkedHashMap<>();values.forEach(v->m.put(id.apply(v),v));return m;}
    private static String id(String value,String prefix,int number){return blank(value)?prefix+number:value.replaceAll("[^A-Za-z0-9_-]","");}private static String cleanTitle(String v,String d){return blank(v)?d:v.trim();}private static String card(String v){return "1".equals(v)?"1":"M".equalsIgnoreCase(v)?"M":"N";}private static String nz(String v){return v==null?"":v;}private static boolean blank(String v){return v==null||v.isBlank();}private static <T> List<T> safe(List<T> v){return v==null?List.of():v;}private static List<Warning> warnings(List<Warning> v){return safe(v);}
    private static DiagramGenerationException invalid(String message){return new DiagramGenerationException("DIAGRAM_RELATION_INVALID",message+"，原图已恢复。");}
}
