package com.dropai.rewrite.service.diagram;

import com.dropai.rewrite.config.DiagramAssistantProperties;
import com.dropai.rewrite.service.diagram.DiagramIr.*;
import com.dropai.rewrite.service.diagram.SqlSchemaExtractor.*;
import org.springframework.stereotype.Component;
import java.util.*;

@Component
public class SqlRelationResolver {
    private final DiagramAssistantProperties properties; public SqlRelationResolver(DiagramAssistantProperties properties){this.properties=properties;}
    public ErDiagramIr resolve(SqlSchema schema,String title){Map<String,Table> tables=new LinkedHashMap<>();schema.tables().forEach(t->tables.put(t.name(),t));List<ErEntity> entities=new ArrayList<>();Map<String,Integer> referenced=new HashMap<>();
        for(Table t:schema.tables()){Set<String> pk=flatten(t.primaryKeys());for(Column c:t.columns().values())if(c.inlinePrimaryKey())pk.add(c.name());Set<String> uq=flatten(t.uniqueKeys());for(Column c:t.columns().values())if(c.inlineUnique())uq.add(c.name());Set<String> fk=t.foreignKeys().stream().flatMap(x->x.sourceColumns().stream()).collect(java.util.stream.Collectors.toSet());boolean assoc=t.foreignKeys().size()>=2&&(containsKey(t.primaryKeys(),fk)||containsKey(t.uniqueKeys(),fk));List<ErAttribute> attrs=t.columns().values().stream().map(c->new ErAttribute(c.name(),blank(c.comment())?c.name():c.comment(),c.type(),pk.contains(c.name()),fk.contains(c.name()),uq.contains(c.name()),!c.notNull())).toList();entities.add(new ErEntity(t.name(),blank(t.comment())?t.name():t.comment(),attrs,assoc));}
        List<ErRelation> relations=new ArrayList<>();Set<String> relatedFields=new HashSet<>();for(Table t:schema.tables())for(ForeignKey fk:t.foreignKeys()){if(!tables.containsKey(fk.targetTable()))throw new DiagramGenerationException("SQL_PARSE_FAILED","外键引用不存在的表："+fk.targetTable());boolean one=isUniqueOrPrimary(t,fk.sourceColumns());String key=t.name()+"."+String.join(",",fk.sourceColumns());relatedFields.add(key);referenced.merge(fk.targetTable(),1,Integer::sum);relations.add(new ErRelation("r"+(relations.size()+1),fk.targetTable(),String.join(",",fk.targetColumns()),t.name(),String.join(",",fk.sourceColumns()),"1",one?"1":"N","引用",RelationSource.DECLARED,1d));}
        List<Warning> warnings=new ArrayList<>();for(Table t:schema.tables())for(Column c:t.columns().values()){String key=t.name()+"."+c.name();if(relatedFields.contains(key)||!c.name().toLowerCase().endsWith("_id"))continue;String base=c.name().substring(0,c.name().length()-3).toLowerCase();List<Table> candidates=schema.tables().stream().filter(q->q.name().equalsIgnoreCase(base)||q.name().equalsIgnoreCase(base+"s")||singular(q.name()).equals(base)).filter(q->q.columns().containsKey("id")&&compatible(c.type(),q.columns().get("id").type())).toList();if(candidates.size()==1){double confidence=.9;Table target=candidates.get(0);if(confidence>=properties.getSqlInferenceConfidenceThreshold()){referenced.merge(target.name(),1,Integer::sum);relations.add(new ErRelation("r"+(relations.size()+1),target.name(),"id",t.name(),c.name(),"1",isUniqueOrPrimary(t,List.of(c.name()))?"1":"N","推断引用",RelationSource.INFERRED,confidence));}else warnings.add(new Warning("LOW_CONFIDENCE_RELATION",key+" 可能引用 "+target.name()+".id",confidence));}}
        List<String> core=entities.stream().filter(e->!e.associationEntity()).sorted(Comparator.<ErEntity>comparingInt(e->referenced.getOrDefault(e.id(),0)).reversed().thenComparingInt(e->e.attributes().size()).reversed()).limit(Math.min(3,entities.size())).map(ErEntity::id).toList();return new ErDiagramIr("1.0",DiagramType.ER_DIAGRAM,blank(title)?"数据库ER图":title,entities,relations,core,warnings);}
    private static boolean isUniqueOrPrimary(Table t,List<String> cols){Set<String> s=new HashSet<>(cols);if(cols.size()==1){Column c=t.columns().get(cols.get(0));if(c!=null&&(c.inlinePrimaryKey()||c.inlineUnique()))return true;}return containsKey(t.primaryKeys(),s)||containsKey(t.uniqueKeys(),s);}private static boolean containsKey(List<List<String>> keys,Set<String> cols){return keys.stream().anyMatch(k->new HashSet<>(k).equals(cols));}private static Set<String> flatten(List<List<String>> v){Set<String>s=new HashSet<>();v.forEach(s::addAll);return s;}private static String singular(String s){String v=s.toLowerCase();return v.endsWith("ies")?v.substring(0,v.length()-3)+"y":v.endsWith("s")?v.substring(0,v.length()-1):v;}private static boolean compatible(String a,String b){String x=a.replaceAll("\\([^)]*\\)","").trim(),y=b.replaceAll("\\([^)]*\\)","").trim();return x.equalsIgnoreCase(y)||x.contains("int")&&y.contains("int");}private static boolean blank(String s){return s==null||s.isBlank();}
}
