package com.dropai.rewrite.mechanicalengine.service;

import com.dropai.rewrite.auth.AuthContext;
import com.dropai.rewrite.entity.DocumentJobRecord;
import com.dropai.rewrite.mapper.DocumentJobMapper;
import com.dropai.rewrite.mechanicalengine.cad.SolidWorksExecutor;
import com.dropai.rewrite.mechanicalengine.cad.SolidWorksScriptGenerator;
import com.dropai.rewrite.mechanicalengine.domain.MechanicalProject;
import com.dropai.rewrite.mechanicalengine.validation.MechanicalArtifactValidator;
import org.springframework.stereotype.Service;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;

@Service
public class MechanicalEngineService {
    private final MechanicalChiefEngineer chiefEngineer;
    private final SolidWorksScriptGenerator scriptGenerator;
    private final SolidWorksExecutor executor;
    private final MechanicalArtifactValidator validator;
    private final MechanicalPackageBuilder packageBuilder;
    private final DocumentJobMapper mapper;

    public MechanicalEngineService(MechanicalChiefEngineer chiefEngineer, SolidWorksScriptGenerator scriptGenerator,
                                   SolidWorksExecutor executor, MechanicalArtifactValidator validator,
                                   MechanicalPackageBuilder packageBuilder, DocumentJobMapper mapper) {
        this.chiefEngineer = chiefEngineer;
        this.scriptGenerator = scriptGenerator;
        this.executor = executor;
        this.validator = validator;
        this.packageBuilder = packageBuilder;
        this.mapper = mapper;
    }

    public MechanicalProject execute(String requirementText) {
        MechanicalProject project = chiefEngineer.design(requirementText);
        pass(project, "REQUIREMENT_UNDERSTANDING", "Functional requirements extracted; task dimensions are not copied into CAD.");
        pass(project, "MECHANICAL_DESIGN", "Mechanical concept and module architecture generated.");
        pass(project, "PARAMETER_GENERATION", "Engineering parameters generated with design rationale.");
        pass(project, "ASSEMBLY_ARCHITECTURE", "Components, poses, and assembly mates defined.");
        pass(project, "PART_DESIGN", "SolidWorks feature plans generated for every part.");

        Path workspace;
        try {
            workspace = Files.createTempDirectory("dropai-solidworks-" + project.getProjectId());
        } catch (Exception exception) {
            return fail(project, "WORKSPACE_CREATE_FAILED", exception.getMessage());
        }

        Path script = scriptGenerator.generate(project, workspace);
        pass(project, "SOLIDWORKS_SCRIPT", "SolidWorks API automation script generated.");
        running(project, "SOLIDWORKS_EXECUTION", "Calling the Windows SolidWorks worker.");
        SolidWorksExecutor.ExecutionResult execution = executor.execute(script, workspace);
        if (!execution.success()) return fail(project, execution.errorCode(), execution.message());
        pass(project, "SOLIDWORKS_EXECUTION", "Native SolidWorks models and drawings generated by the worker.");

        MechanicalArtifactValidator.ValidationReport report = validator.validate(project, workspace);
        if (!report.passed()) return fail(project, "ARTIFACT_VALIDATION_FAILED", String.join("; ", report.errors()));
        addValidatedArtifacts(project, workspace);
        pass(project, "STEP_VALIDATION", "STEP integrity and FreeCAD reopen validation passed.");
        pass(project, "DRAWING_EXPORT", "SolidWorks DWG and PDF drawing validation passed.");

        byte[] packageBytes = packageBuilder.build(workspace);
        project.getArtifacts().add(persist(project, packageBytes));
        pass(project, "PACKAGE", "Mechanical_Project.zip completed.");
        project.setStatus("COMPLETED");
        project.setCurrentStage("COMPLETED");
        return project;
    }

    private void addValidatedArtifacts(MechanicalProject project, Path workspace) {
        addArtifact(project, workspace, "02_STEP/Assembly.STEP", "model/step");
        addArtifact(project, workspace, "02_STEP/freecad-preview.png", "image/png");
        addArtifact(project, workspace, "03_Drawing/Assembly.DWG", "application/acad");
        addArtifact(project, workspace, "04_Document/Design_Report.pdf", "application/pdf");
    }

    private void addArtifact(MechanicalProject project, Path workspace, String relativePath, String mediaType) {
        try {
            Path file = workspace.resolve(relativePath);
            project.getArtifacts().add(new MechanicalProject.Artifact(relativePath, mediaType, Files.size(file), "", true));
        } catch (Exception exception) {
            throw new IllegalStateException("VALIDATED_ARTIFACT_METADATA_FAILED: " + relativePath, exception);
        }
    }

    private MechanicalProject.Artifact persist(MechanicalProject project, byte[] content) {
        Long userId = AuthContext.requireUserId();
        DocumentJobRecord record = new DocumentJobRecord();
        record.setJobId(project.getProjectId());
        record.setUserId(userId);
        record.setFileName("Mechanical_Project.zip");
        record.setSourceFeature("MECHANICAL_ENGINE");
        record.setMode("zip");
        record.setModeName("Mechanical Project");
        record.setPlatform("SOLIDWORKS");
        record.setPlatformName("SolidWorks Automation");
        record.setStatus("SUCCESS");
        record.setTotalParagraphs(1);
        record.setProcessedParagraphs(1);
        record.setRewrittenParagraphs(1);
        record.setMessage("Validated SolidWorks mechanical project package");
        record.setParagraphsJson("[]");
        record.setOutputFile(content);
        record.setCreatedAt(LocalDateTime.now());
        record.setUpdatedAt(LocalDateTime.now());
        mapper.insert(record);
        return new MechanicalProject.Artifact("Mechanical_Project.zip", "application/zip", content.length,
                "/api/documents/" + record.getJobId() + "/download", true);
    }

    private void pass(MechanicalProject project, String stage, String message) {
        project.setCurrentStage(stage);
        project.getStages().add(new MechanicalProject.StageState(stage, "PASSED", message));
    }

    private void running(MechanicalProject project, String stage, String message) {
        project.setStatus("RUNNING");
        project.setCurrentStage(stage);
        project.getStages().add(new MechanicalProject.StageState(stage, "RUNNING", message));
    }

    private MechanicalProject fail(MechanicalProject project, String code, String message) {
        project.setStatus("DESIGN_FAILED");
        project.setFailureCode(code);
        project.setFailureMessage(message == null ? "" : message);
        project.getStages().add(new MechanicalProject.StageState(project.getCurrentStage(), "FAILED", project.getFailureMessage()));
        return project;
    }
}
