<template>
  <main class="ppt-page">
    <nav><button @click="router.push('/dashboard')">Dokiai Academic</button><span>PPT 智能生成</span></nav>
    <header><small>AI PRESENTATION WORKFLOW</small><h1>从完整源文件生成可编辑 PPTX</h1><p>源文件决定事实和素材，一级大纲决定结构；系统按顺序逐页制作并检查。</p></header>

    <section v-if="stage === 'upload'" class="card upload-grid">
      <div><h2>上传完整源文件</h2><p>PPTX 为主要输入，也支持完整 DOCX 与 PDF。表单、封面或空模板不会进入生成流程。</p><label class="drop"><input type="file" accept=".pptx,.docx,.pdf" @change="file=$event.target.files?.[0]||null"><b>＋</b><span>{{ file?.name || '选择文件' }}</span><small>{{ file ? formatBytes(file.size) : '最大 80 MB' }}</small></label></div>
      <div class="fields"><h2>答辩信息</h2><label>题目<input v-model="form.topic" placeholder="可从源文件提取"></label><label>汇报人<input v-model="form.presenter"></label><label>专业<input v-model="form.major"></label><label>指导教师<input v-model="form.advisor"></label><label>学号<input v-model="form.studentNumber"></label><button :disabled="!file||busy" @click="start">{{ busy ? statusText : '解析并生成 →' }}</button></div>
    </section>

    <section v-else class="workflow">
      <article class="card analysis"><h2>资源分析</h2><div class="metrics"><span><b>{{ analysis.precheck?.validChapterCount || analysis.headings?.length || 0 }}</b>有效章节</span><span><b>{{ analysis.imageCount || 0 }}</b>图片总数</span><span><b>{{ analysis.validImageCount || 0 }}</b>有效正文图片</span><span><b>{{ analysis.filteredAssetCount || 0 }}</b>过滤素材</span><span><b>{{ analysis.tableCount || 0 }}</b>表格</span></div><p :class="analysis.precheck?.passed ? 'ok' : 'error'">{{ analysis.precheck?.message || statusText }}</p></article>
      <article class="card"><div class="title-row"><div><small>一级大纲 · 最多 5 项</small><h2>生成期间仍可调整大纲</h2></div><button class="ghost" :disabled="busy||outline.length>=5" @click="outline.push({title:'新目录',description:'',target_slides:1})">＋ 新增</button></div>
        <div class="outline"><div v-for="(item,i) in outline" :key="item.id||i"><b>{{ String(i+1).padStart(2,'0') }}</b><input v-model="item.title" maxlength="20"><span><button :disabled="i===0" @click="move(i,-1)">↑</button><button :disabled="i===outline.length-1" @click="move(i,1)">↓</button><button :disabled="outline.length<=2" @click="outline.splice(i,1)">×</button></span></div></div>
        <button class="save" :disabled="outline.length<2||outline.length>5" @click="saveOutlineOnly">保存大纲变更</button>
      </article>
      <article class="card progress"><div><small>{{ statusText }}</small><h2>{{ project.current_stage || '正在按顺序制作页面' }}</h2><p>当前页面：{{ currentPage }} / {{ totalPages }}　已完成：{{ completedPages }}　失败：{{ failedPages }}</p></div><strong>{{ project.progress || 0 }}%</strong><div class="bar"><i :style="{width:(project.progress||0)+'%'}"></i></div></article>
      <article v-if="stage==='done'" class="card done"><h2>生成完成</h2><p>文本、图片、标题、页码和表格均保持为独立可编辑对象。</p><button @click="download">下载 {{ cleanTopic }}.pptx</button></article>
    </section>
  </main>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import { createPptProject,getPptProject,uploadPptSource,analyzePptProject,generatePptOutline,savePptOutline,planPptSlides,generatePptFile,getPptProgress,downloadPptFile } from '../../api/rewrite';
const router=useRouter(),route=useRoute(),stage=ref('upload'),busy=ref(false),file=ref(null),project=ref({progress:0}),analysis=ref({}),outline=ref([]),pages=ref([]),statusText=ref('等待上传');
const form=ref({topic:'',presenter:'',major:'',advisor:'',studentNumber:'',targetSlideCount:16});
const cleanTopic=computed(()=>String(project.value.topic||form.value.topic||'未命名学术答辩').replace(/[\\/:*?"<>|]/g,'_'));
const currentPage=computed(()=>Math.min(completedPages.value+1,totalPages.value)),totalPages=computed(()=>pages.value.length+outline.value.length+4),completedPages=computed(()=>pages.value.filter(x=>x.status==='SUCCESS').length),failedPages=computed(()=>pages.value.filter(x=>x.status==='FAILED').length);
function formatBytes(n){return n>1048576?(n/1048576).toFixed(1)+' MB':(n/1024).toFixed(1)+' KB'}
function move(i,d){const n=i+d;if(n<0||n>=outline.value.length)return;[outline.value[i],outline.value[n]]=[outline.value[n],outline.value[i]]}
async function start(){busy.value=true;try{project.value=await createPptProject(form.value);project.value=await uploadPptSource(project.value.id,file.value);project.value=await analyzePptProject(project.value.id);analysis.value=JSON.parse(project.value.analysis_json||'{}');const out=await generatePptOutline(project.value.id);project.value=out;outline.value=out.outline||[];statusText.value='内容规划完成';stage.value='running';await new Promise(r=>setTimeout(r,0));await saveOutlineOnly(false);const planned=await planPptSlides(project.value.id);project.value=planned;pages.value=planned.slides||[];statusText.value='素材绑定完成';await new Promise(r=>setTimeout(r,0));statusText.value='版式规划完成';await new Promise(r=>setTimeout(r,0));statusText.value='正在生成PPT';await generatePptFile(project.value.id);project.value=await getPptProgress(project.value.id);pages.value=project.value.slides||pages.value;statusText.value='生成完成';stage.value='done'}catch(e){ElMessage.error(e?.responseData?.message||e.message||'生成失败')}finally{busy.value=false}}
async function saveOutlineOnly(notify=true){const data=await savePptOutline(project.value.id,outline.value.map((x,i)=>({id:x.id,title:x.title,description:x.description||'',targetSlides:Math.min(2,Math.max(1,x.target_slides||1)),sectionOrder:i+1})));outline.value=data.outline||outline.value;if(notify)ElMessage.success('仅受影响页面已加入处理队列')}
async function download(){const blob=await downloadPptFile(project.value.id),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=cleanTopic.value+'.pptx';a.click();URL.revokeObjectURL(url)}
onMounted(async()=>{if(!route.query.projectId)return;try{const data=await getPptProject(route.query.projectId);project.value=data;outline.value=data.outline||[];pages.value=data.slides||[];analysis.value=JSON.parse(data.analysis_json||'{}');stage.value=data.status==='SUCCESS'?'done':data.status==='DRAFT'?'upload':'running'}catch(e){ElMessage.warning('项目无法恢复')}});
</script>

<style scoped>
.ppt-page{min-height:100vh;padding:24px;background:linear-gradient(145deg,#f6f4ff,#fff8fb);color:#25283a}nav{display:flex;justify-content:space-between;max-width:1180px;margin:auto}nav button{border:0;background:none;font-weight:900}.ppt-page>header{max-width:1180px;margin:54px auto 30px}.ppt-page>header h1{font-size:42px;margin:8px 0}.ppt-page>header p,.card p{color:#767b8d}.card{max-width:1120px;margin:16px auto;padding:30px;border:1px solid #ebe6f4;border-radius:24px;background:#fffffff0;box-shadow:0 20px 60px #49367a10}.upload-grid{display:grid;grid-template-columns:1fr 1fr;gap:34px}.drop{display:grid;place-items:center;gap:8px;padding:54px;border:1px dashed #9e8de5;border-radius:18px}.drop input{display:none}.drop b{font-size:34px;color:#7657e9}.fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}.fields h2,.fields button{grid-column:1/-1}label{display:grid;gap:6px;font-size:12px;color:#777d8f}input{padding:12px;border:1px solid #ded9eb;border-radius:10px}button{cursor:pointer}.fields button,.save,.done button{padding:13px;border:0;border-radius:11px;color:white;background:linear-gradient(120deg,#7050ef,#e653a3)}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.metrics span{display:grid;padding:15px;border-radius:14px;background:#f6f3ff;color:#7a7f90}.metrics b{font-size:27px;color:#25283a}.ok{color:#18705f!important}.error{color:#b9324d!important}.title-row,.outline>div,.progress{display:flex;align-items:center;justify-content:space-between;gap:16px}.ghost{padding:9px 13px;border:1px solid #8f7ae7;border-radius:10px;background:#fff;color:#6952cd}.outline{display:grid;gap:9px}.outline>div{padding:12px;border:1px solid #ebe6f2;border-radius:13px}.outline input{flex:1}.outline b{color:#7050ef}.outline span button{border:0;background:none;color:#7050ef}.save{margin-top:14px}.progress{flex-wrap:wrap}.progress strong{font-size:30px}.bar{width:100%;height:8px;border-radius:8px;background:#ebe7f2;overflow:hidden}.bar i{display:block;height:100%;background:linear-gradient(90deg,#7050ef,#ec58a4)}.done{text-align:center}@media(max-width:760px){.upload-grid{grid-template-columns:1fr}.metrics{grid-template-columns:repeat(2,1fr)}.ppt-page>header h1{font-size:30px}}
</style>
